### ISSUE TITLE
memory leak when IPAM fails with "Received invalid state update!"

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1329]
From https://github.com/weaveworks/weave/issues/1178#issuecomment-132323364

Running
```
host1$ sudo weave launch-router
host1$ sudo weave run -ti ubuntu
host2$ sudo weave launch-router
host2$ sudo weave run -ti ubuntu
host1$ sudo weave connect host2
```
results in an ever increasing memory usage of the two weave routers.

**Comment by rade** [comment]
Curiously the memory growth rate is much reduced when I run the 2nd peer on my main desktop instead of a VM.

From the heap profile it looks like we are leaking `NonEncryptor`s and `Forwarder`s:

```
154: 10092544 [154: 10092544] @ 0x42375c 0x4ae313 0x4a5740 0x448221
#	0x4ae313	github.com/weaveworks/weave/router.(*LocalConnection).ensureForwarders+0x583	/home/matthias/go/src/github.com/weaveworks/weave/router/forwarder.go:37
#	0x4a5740	github.com/weaveworks/weave/router.(*LocalConnection).run+0x550			/home/matthias/go/src/github.com/weaveworks/weave/router/connection.go:312

148: 9699328 [150: 9830400] @ 0x42375c 0x4ae524 0x4a5740 0x448221
#	0x4ae524	github.com/weaveworks/weave/router.(*LocalConnection).ensureForwarders+0x794	/home/matthias/go/src/github.com/weaveworks/weave/router/forwarder.go:38
#	0x4a5740	github.com/weaveworks/weave/router.(*LocalConnection).run+0x550			/home/matthias/go/src/github.com/weaveworks/weave/router/connection.go:312

40: 2621440 [41: 2686976] @ 0x42375c 0x6bf4ba 0x6b7381 0x6c0999 0x6bfaf1 0x4c7042 0x4b0147 0x4afc87 0x4b0b6e 0x448221
#	0x6bf4ba	github.com/google/gopacket.(*serializeBuffer).PrependBytes+0x10a		/home/matthias/go/src/github.com/google/gopacket/writer.go:139
#	0x6b7381	github.com/google/gopacket.Payload.SerializeTo+0x61				/home/matthias/go/src/github.com/google/gopacket/base.go:52
#	0x6c0999	github.com/google/gopacket.(*Payload).SerializeTo+0xd9				<autogenerated>:8
#	0x6bfaf1	github.com/google/gopacket.SerializeLayers+0xc1					/home/matthias/go/src/github.com/google/gopacket/writer.go:190
#	0x4c7042	github.com/weaveworks/weave/router.(*RawUDPSender).Send+0x212			/home/matthias/go/src/github.com/weaveworks/weave/router/udp_sender.go:74
#	0x4b0147	github.com/weaveworks/weave/router.(*Forwarder).flush+0x107			/home/matthias/go/src/github.com/weaveworks/weave/router/forwarder.go:301
#	0x4afc87	github.com/weaveworks/weave/router.(*Forwarder).accumulateAndSendFrames+0x147	/home/matthias/go/src/github.com/weaveworks/weave/router/forwarder.go:277
#	0x4b0b6e	github.com/weaveworks/weave/router.(*ForwarderDF).run+0x42e			/home/matthias/go/src/github.com/weaveworks/weave/router/forwarder.go:380
```

But from a stack dump it looks like we are leaking `GossipSender`s; I've got >1800 of these:
```
goroutine 23443 [select]:
github.com/weaveworks/weave/router.(*GossipSender).run(0xc21ad48b60)
	/home/matthias/go/src/github.com/weaveworks/weave/router/gossip.go:56 +0x22c
created by github.com/weaveworks/weave/router.NewGossipSender
	/home/matthias/go/src/github.com/weaveworks/weave/router/gossip.go:50 +0x111
```

**Comment by rade** [comment]
Some instrumentation reveals the following:
```
INFO: 2015/08/19 08:05:35.339953 [gossip topology]: collected 6 of 19 senders when there are 1 connections
INFO: 2015/08/19 08:05:35.340021 [gossip IPallocation]: collected 14 of 19 senders when there are 1 connections
INFO: 2015/08/19 08:05:35.340174 [gossip nameserver]: collected 18 of 19 senders when there are 1 connections
INFO: 2015/08/19 08:07:35.340143 [gossip nameserver]: collected 214 of 251 senders when there are 1 connections
INFO: 2015/08/19 08:07:35.340231 [gossip topology]: collected 2 of 263 senders when there are 1 connections
INFO: 2015/08/19 08:07:35.340331 [gossip IPallocation]: collected 16 of 255 senders when there are 1 connections
INFO: 2015/08/19 08:08:35.340009 [gossip topology]: collected 42 of 368 senders when there are 1 connections
INFO: 2015/08/19 08:08:35.340231 [gossip IPallocation]: collected 56 of 346 senders when there are 1 connections
INFO: 2015/08/19 08:08:35.340357 [gossip nameserver]: collected 119 of 144 senders when there are 1 connections
```

So the sender gc is functioning as expected but is running very infrequently.

This suggests that most of the senders get created in the GossipChannel.Send's invocation of sendDown, which is no preceded by a sender gc. Easy to change but adds an O(n_connections) (or worse) to this path since we need to obtain the list of all connections.

**Comment by rade** [comment]
> Curiously the memory growth rate is much reduced when I run the 2nd peer on my main desktop instead of a VM.

It turns out that I ended up in a slightly different configuration, with the error being "Received new version for entry I own!". Repeating the test, and now getting the ""Received invalid state update!" error, I now see a higher growth rate. And no invocations of the gc! Presumably because we never do a GossipChannel.Send, only SendDown.

**Comment by rade** [comment]
So for this to occur, the weave router must not have any successfully established, durable connections - since having even one of those will result in the GossipSender gc path getting invoked regularly - and it must continuously make connections that get torn down after they have completed the handshake.
