### ISSUE TITLE
"growslice: cap out of range" panic in gob encoding

### ISSUE THREAD

**Issue by MaximeHeckel** [weaveworks/weave#1450]
While trying the `-initpeercount` flag (set to a wrong number to see the effects) one of the weave 1.0.3 routers crashed.

Here are the logs:

```
weave 2015/09/18 16:19:16.475139 ->[192.81.217.207:6783] attempting connection
weave 2015/09/18 16:19:16.477903 ->[192.81.217.207:6783] error during connection attempt: dial tcp4 192.81.217.207:6783: connection refused
weave 2015/09/18 16:19:16.532717 ->[192.241.130.141:6783] attempting connection
weave 2015/09/18 16:19:16.543436 ->[192.241.130.141:6783] error during connection attempt: dial tcp4 192.241.130.141:6783: connection refused
weave 2015/09/18 16:19:18.896839 ->[192.81.217.207:6783] attempting connection
weave 2015/09/18 16:19:18.899240 ->[192.81.217.207:6783] error during connection attempt: dial tcp4 192.81.217.207:6783: connection refused
weave 2015/09/18 16:19:19.505453 ->[192.241.130.141:6783] attempting connection
weave 2015/09/18 16:19:19.509241 ->[192.241.130.141:6783] error during connection attempt: dial tcp4 192.241.130.141:6783: connection refused
panic: runtime error: growslice: cap out of range [recovered]
	panic: runtime error: growslice: cap out of range

goroutine 44 [running]:
encoding/gob.catchError(0xc209bb4630)
	/usr/local/go/src/encoding/gob/error.go:38 +0x96
encoding/gob.encUint8Array(0xc20917dd40, 0xc209b99e00, 0x89b100, 0xc209bc0120, 0x57)
	/usr/local/go/src/encoding/gob/encode.go:238 +0x17b
encoding/gob.(*Encoder).encodeSingle(0xc209bb45a0, 0xc209bb45d8, 0xc209173200, 0x89b100, 0xc209bc0120, 0x57)
	/usr/local/go/src/encoding/gob/encode.go:294 +0x17b
encoding/gob.(*Encoder).encode(0xc209bb45a0, 0xc209bb45d8, 0x89b100, 0xc209bc0120, 0x57, 0xc208034280)
	/usr/local/go/src/encoding/gob/encode.go:694 +0x20f
encoding/gob.(*Encoder).EncodeValue(0xc209bb45a0, 0x89b100, 0xc209bc0120, 0x57, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:241 +0x613
encoding/gob.(*Encoder).Encode(0xc209bb45a0, 0x89b100, 0xc209bc0120, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:168 +0x7f
github.com/weaveworks/weave/router.GobEncode(0xc2092e5e88, 0x3, 0x3, 0x0, 0x0, 0x0)
	/home/vagrant/src/github.com/weaveworks/weave/router/utils.go:80 +0x130
github.com/weaveworks/weave/router.func·016(0x7ff7ac9bc260, 0xc209b81e60)
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip_channel.go:157 +0x290
github.com/weaveworks/weave/router.(*GossipSender).run(0xc20943b060)
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:59 +0xf6
created by github.com/weaveworks/weave/router.(*GossipSender).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:49 +0xac

goroutine 1 [chan receive, 12 minutes]:
github.com/weaveworks/weave/common.SignalHandlerLoop(0xc2094e7e68, 0x1, 0x1)
	/home/vagrant/src/github.com/weaveworks/weave/common/signals.go:21 +0x2a4
main.main()
	/home/vagrant/src/github.com/weaveworks/weave/releases/v1.0.3/prog/weaver/main.go:170 +0x1d98

goroutine 5 [syscall, 12 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [select]:
github.com/weaveworks/weave/ipam.(*Allocator).actorLoop(0xc2091223c0, 0xc20800c540)
	/home/vagrant/src/github.com/weaveworks/weave/ipam/allocator.go:461 +0x14a
created by github.com/weaveworks/weave/ipam.(*Allocator).Start
	/home/vagrant/src/github.com/weaveworks/weave/ipam/allocator.go:79 +0x79

goroutine 7 [select]:
github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xc20911ca80, 0xc209108980)
	/home/vagrant/src/github.com/fsouza/go-dockerclient/event.go:176 +0x419
created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
	/home/vagrant/src/github.com/fsouza/go-dockerclient/event.go:143 +0x16f

goroutine 9 [chan receive]:
github.com/weaveworks/weave/common/docker.func·001()
	/home/vagrant/src/github.com/weaveworks/weave/common/docker/client.go:52 +0x5c
created by github.com/weaveworks/weave/common/docker.(*Client).AddObserver
	/home/vagrant/src/github.com/weaveworks/weave/common/docker/client.go:59 +0x251

goroutine 17 [syscall, 12 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [select]:
github.com/weaveworks/weave/router.(*LocalPeer).actorLoop(0xc2090d5b30, 0xc20800c720)
	/home/vagrant/src/github.com/weaveworks/weave/router/local_peer.go:173 +0x101
created by github.com/weaveworks/weave/router.(*LocalPeer).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/local_peer.go:27 +0x7e

goroutine 11 [select]:
github.com/weaveworks/weave/router.(*Routes).run(0xc20800c4e0, 0xc20800c780, 0xc20800c7e0)
	/home/vagrant/src/github.com/weaveworks/weave/router/routes.go:154 +0x132
created by github.com/weaveworks/weave/router.(*Routes).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/routes.go:44 +0xd4

goroutine 12 [select]:
github.com/weaveworks/weave/router.(*ConnectionMaker).queryLoop(0xc20912c4c0, 0xc20800c840)
	/home/vagrant/src/github.com/weaveworks/weave/router/connection_maker.go:166 +0x162
created by github.com/weaveworks/weave/router.(*ConnectionMaker).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/connection_maker.go:52 +0x7e

goroutine 13 [syscall]:
syscall.Syscall6(0x2d, 0x8, 0xc2091b1e91, 0xffff, 0x0, 0xc2091b1c50, 0xc2091b1c4c, 0x259e325d3b1e1243, 0x564744aecc4faa84, 0x5d441877ed782eef)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.recvfrom(0x8, 0xc2091b1e91, 0xffff, 0xffff, 0x0, 0xc2091b1c50, 0xc2091b1c4c, 0x58, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1906 +0x9b
syscall.Recvfrom(0x8, 0xc2091b1e91, 0xffff, 0xffff, 0x0, 0x6, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:220 +0xbf
net.(*netFD).readFrom(0xc20911cd20, 0xc2091b1e91, 0xffff, 0xffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:265 +0x38c
net.(*UDPConn).ReadFromUDP(0xc208036110, 0xc2091b1e91, 0xffff, 0xffff, 0xc2093e43f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/udpsock_posix.go:67 +0x124
github.com/weaveworks/weave/router.(*Router).udpReader(0xc2080c8420, 0xc208036110, 0x7ff7ac9bb088, 0xc2080360f8)
	/home/vagrant/src/github.com/weaveworks/weave/router/router.go:255 +0xfb
created by github.com/weaveworks/weave/router.(*Router).listenUDP
	/home/vagrant/src/github.com/weaveworks/weave/router/router.go:246 +0x324

goroutine 14 [IO wait, 12 minutes]:
net.(*pollDesc).Wait(0xc20911cdf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20911cdf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20911cd90, 0x0, 0x7ff7ae3fb730, 0xc2091701e8)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036130, 0xc209140038, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/weaveworks/weave/router.func·029()
	/home/vagrant/src/github.com/weaveworks/weave/router/router.go:212 +0x5e
created by github.com/weaveworks/weave/router.(*Router).listenTCP
	/home/vagrant/src/github.com/weaveworks/weave/router/router.go:220 +0x2e4

goroutine 15 [syscall, locked to thread]:
github.com/google/gopacket/pcap._Cfunc_pcap_next_ex(0x30d03d0, 0xc20912c768, 0xc20912c770, 0x0)
	/home/vagrant/src/github.com/google/gopacket/pcap/:172 +0x43
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc20912c740, 0xc209155ef8, 0x0, 0x0)
	/home/vagrant/src/github.com/google/gopacket/pcap/pcap.go:306 +0x92
github.com/google/gopacket/pcap.(*Handle).ZeroCopyReadPacketData(0xc20912c740, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vagrant/src/github.com/google/gopacket/pcap/pcap.go:338 +0xb0
github.com/weaveworks/weave/router.(*PcapIO).ReadPacket(0xc2080360f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/src/github.com/weaveworks/weave/router/pcap.go:76 +0x67
github.com/weaveworks/weave/router.func·028()
	/home/vagrant/src/github.com/weaveworks/weave/router/router.go:144 +0x5d
created by github.com/weaveworks/weave/router.(*Router).sniff
	/home/vagrant/src/github.com/weaveworks/weave/router/router.go:149 +0x40f

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2092d32c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2092d32c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2092d3260, 0x0, 0x7ff7ae3fb730, 0xc208d79208)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036350, 0xc2092e8cf8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036350, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20800db00, 0x7ff7ac9bb740, 0xc208036350, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7ff7ac9bb740, 0xc208036350, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1606 +0xa1
main.handleHTTP(0xc2080c8420, 0xc2090d7cb8, 0x5, 0xc2091223c0, 0xa800000, 0xa, 0xc2080360c0)
	/home/vagrant/src/github.com/weaveworks/weave/releases/v1.0.3/prog/weaver/main.go:304 +0x8ff
created by main.main
	/home/vagrant/src/github.com/weaveworks/weave/releases/v1.0.3/prog/weaver/main.go:167 +0x1c88

goroutine 20 [select]:
github.com/weaveworks/weave/router.(*GossipSender).run(0xc209172e60)
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:54 +0x22c
created by github.com/weaveworks/weave/router.(*GossipSender).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:49 +0xac

goroutine 19 [select]:
github.com/weaveworks/weave/router.(*LocalConnection).actorLoop(0xc2092e0000, 0xc209178180, 0x0, 0x0)
	/home/vagrant/src/github.com/weaveworks/weave/router/connection.go:375 +0x2d9
github.com/weaveworks/weave/router.(*LocalConnection).run(0xc2092e0000, 0xc209178180, 0xc2091781e0, 0x9d8b01)
	/home/vagrant/src/github.com/weaveworks/weave/router/connection.go:310 +0x382
created by github.com/weaveworks/weave/router.(*LocalConnection).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/connection.go:121 +0xdd

goroutine 21 [select]:
github.com/weaveworks/weave/router.(*GossipSender).run(0xc209172ea0)
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:54 +0x22c
created by github.com/weaveworks/weave/router.(*GossipSender).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:49 +0xac

goroutine 22 [select, 10 minutes]:
github.com/weaveworks/weave/router.(*GossipSender).run(0xc209172ee0)
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:54 +0x22c
created by github.com/weaveworks/weave/router.(*GossipSender).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:49 +0xac

goroutine 23 [IO wait]:
net.(*pollDesc).Wait(0xc209174220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209174220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2091741c0, 0xc2092ea000, 0x1000, 0x1000, 0x0, 0x7ff7ae3fb730, 0xc209059d08)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209140038, 0xc2092ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2091782a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2091782a0, 0xc209170240, 0x1, 0x9, 0xc209da6a50, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7ff7ac9b99f0, 0xc2091782a0, 0xc209170240, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff7ac9b99f0, 0xc2091782a0, 0xc209170240, 0x1, 0x9, 0x20, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7ff7ac9b99f0, 0xc2091782a0, 0xc209170240, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc209176200, 0xc)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc209176200, 0xc2090afa00, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc209176200, 0x87e8a0, 0xc2090afac0, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc209176200, 0x87e8a0, 0xc2090afac0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/weaveworks/weave/router.(*LocalConnection).receiveTCP(0xc2092e0000, 0xc209176200)
	/home/vagrant/src/github.com/weaveworks/weave/router/connection.go:444 +0x10a
created by github.com/weaveworks/weave/router.(*LocalConnection).run
	/home/vagrant/src/github.com/weaveworks/weave/router/connection.go:309 +0x362

goroutine 29 [chan receive]:
github.com/weaveworks/weave/router.(*Forwarder).run(0xc209186b40, 0xc2093481e0, 0xc209348240)
	/home/vagrant/src/github.com/weaveworks/weave/router/forwarder.go:228 +0x89
created by github.com/weaveworks/weave/router.(*Forwarder).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/forwarder.go:211 +0xce

goroutine 35 [chan receive]:
github.com/weaveworks/weave/router.(*Forwarder).run(0xc2091875e0, 0xc209349920, 0xc209349980)
	/home/vagrant/src/github.com/weaveworks/weave/router/forwarder.go:228 +0x89
created by github.com/weaveworks/weave/router.(*Forwarder).Start
	/home/vagrant/src/github.com/weaveworks/weave/router/forwarder.go:211 +0xce

goroutine 27 [select, 10 minutes]:
github.com/weaveworks/weave/router.(*GossipSender).run(0xc209343c40)
	/home/vagrant/src/github.com/weaveworks/weave/router/gossip.go:54 +0x22c
created by github.com/weaveworks/weave/router.(*GossipSender).Start
```

**Comment by rade** [comment]
Is this reproducible?

**Comment by MaximeHeckel** [comment]
As it only happened on 1 of the 2 nodes we've deployed I don't think so but I'll try to reproduce it.

**Comment by bboreham** [comment]
I cannot envisage any way that the code could cause this. The error message is triggered either when the code-generator calls `growslice` with a negative add-on, or the capacity exceeds 128GB. It is inconceivable that weave actually generated a message that large.

I considered whether the memory being encoded could be written by two threads at the same time.  It is a `[][]byte`, which comes from the `Encode()` function on either `TopologyGossipData` or `ipamGossipData`; in both cases it is freshly-allocated and local to the calling goroutine.

Perhaps some random bit-flip due to cosmic rays?

**Comment by rade** [comment]
There are some recent bug fixes in the [slice code](https://github.com/golang/go/commits/master/src/runtime/slice.go), but afaict all the potentially interesting ones pertain to go1.5 and the significant gc changes in that. weave 1.0.3 was built with go 1.4.

**Comment by rade** [comment]
(11:05:51) Bryan Boreham: weaveworks/weave:1.0.2 was built with go1.4; 1.0.3 with go1.4.2
(11:06:09) me: how did you find out?
(11:06:43) Bryan Boreham: 'docker pull' the image; 'docker cp' the binary out; gdb the binary; print 'runtime.buildVersion'

**Comment by bboreham** [comment]
I've had a test program battering away for hours creating and deleting connections, trying to get it to repeat this error, and so far have failed to generate it.

On the other hand, if I take a slice and (via `unsafe`) modify it to have a length > 128GB before passing to `append()`, it happens instantly.

**Comment by bboreham** [comment]
@MaximeHeckel could I ask what kernel this was running on please?

**Comment by MaximeHeckel** [comment]
As I was running a Digital Ocean machine with Ubuntu 14.04 so I would say 3.16

**Comment by rade** [comment]
@MaximeHeckel we added some diagnostics to weave 1.1.1 to help track this down. So if you are seeing this panic again in that version *or* are seeing a "Gossip message too large" panic, please let us know.

**Comment by MaximeHeckel** [comment]
I sure will. We're already testing 1.1.1 with our daemon so far no issues to report.
