### ISSUE TITLE
weave script hangs in IP address allocation after rolling restart

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#1593]
With 1.2.0, if I:

* Start two peers (one just with `weave launch`, one with `weave launch <other's ip>`
* Run a short-lived container on each host in turn: `docker $(weave config) run --name=foo --rm ubuntu ls` (naming the containers seems to be necessary).
* On each host in turn, do `weave reset` and `weave launch` (the latter with the original args).  I.e. at least one router is running throughout.

then further attempt to start containers on the weave network hang (e.g. `weave run -itd ubuntu` on either host).  Seems to be 100% reproducible.  Last few lines with WEAVE_DEBUG=1:

```
+ IPAM_URL=/ip/ab7015b9774d10f7eb365c9f5aa0264d5e6887dc3fb0dc12bc31944d87aefa8b
+ call_weave POST /ip/ab7015b9774d10f7eb365c9f5aa0264d5e6887dc3fb0dc12bc31944d87aefa8b?check-alive=true
+ container_ip weave weave container is not present. Have you launched it? weave container is not running.
+ docker inspect --format={{.State.Running}} {{.NetworkSettings.IPAddress}} weave
+ status=true 
+ CONTAINER_IP=127.0.0.1
+ http_call 127.0.0.1:6784 POST /ip/ab7015b9774d10f7eb365c9f5aa0264d5e6887dc3fb0dc12bc31944d87aefa8b?check-alive=true
+ addr=127.0.0.1:6784
+ http_verb=POST
+ url=/ip/ab7015b9774d10f7eb365c9f5aa0264d5e6887dc3fb0dc12bc31944d87aefa8b?check-alive=true
+ shift 3
+ curl --connect-timeout 3 -s -S -X POST http://127.0.0.1:6784/ip/ab7015b9774d10f7eb365c9f5aa0264d5e6887dc3fb0dc12bc31944d87aefa8b?check-alive=true
```

It's not caused by IPAM consensus woes.  `weave status`:

```
...
       Service: ipam
     Consensus: achieved
         Range: [10.32.0.0-10.48.0.0)
 DefaultSubnet: 10.32.0.0/12
...
```

Nothing obviously interesting in the weave logs.  Last few lines are

```
INFO: 2015/10/27 09:38:39.678852 [allocator]: Allocate request for 973fd8e60a84dc00aa83bef5c4e7c71015b5229c3d9c564586f7e9955699bb57 cancelled
INFO: 2015/10/27 09:41:22.981950 [allocator]: Allocate request for 2ca43780f78dc2809b20ab79401f2d5f7257d37ba0d28b6d3b1ca2e7a0d297fc cancelled
INFO: 2015/10/27 09:42:52.937975 [allocator]: Allocate request for cbb3c83b9b705e327f948d104bcefc5faa954919b408b9e7258452b9c13c43fe cancelled
INFO: 2015/10/27 09:44:52.927980 [allocator]: Allocate request for ab7015b9774d10f7eb365c9f5aa0264d5e6887dc3fb0dc12bc31944d87aefa8b cancelled
```

Due to me killing the hung weave scripts.  So it is getting the HTTP requests, and getting stuck while processing them.

I have my hands full with other stuff today, so I'm not planning to look further into this right now.  Might be good if someone else confirms.

**Comment by awh** [comment]
> Might be good if someone else confirms.

I have reproduced this on the first attempt.

**Comment by rade** [comment]
I doubt this is new in 1.2. @tomwilkiie

**Comment by dpw** [comment]
> I doubt this is new in 1.2. @tomwilkie

Indeed, I can reproduce it in 1.1.2.

Doesn't this somewhat undermine our support for rolling upgrades?

**Comment by rade** [comment]
it's definitely stuck in address allocation. See
```
goroutine 134 [chan receive, 2 minutes]:
github.com/weaveworks/weave/ipam.(*Allocator).Allocate(0xc8212803c0, 0xc8216ca2a9, 0x40, 0xa2fffff0a200001, 0xc8216c8d50, 0x214f3d2d0106e453, 0x0, 0x0)
	/home/matthias/go/src/github.com/weaveworks/weave/ipam/allocator.go:195 +0x155
github.com/weaveworks/weave/ipam.(*Allocator).handleHTTPAllocate(0xc8212803c0, 0xc8212d60c8, 0x7f83fc029308, 0xc8212ffc30, 0xc8216ca2a9, 0x40, 0x41bc01, 0xa200000, 0xc)
	/home/matthias/go/src/github.com/weaveworks/weave/ipam/http.go:44 +0x210
github.com/weaveworks/weave/ipam.(*Allocator).HandleHTTP.func5(0x7f83fc029308, 0xc8212ffc30, 0xc8216669a0)
	/home/matthias/go/src/github.com/weaveworks/weave/ipam/http.go:106 +0x185
net/http.HandlerFunc.ServeHTTP(0xc82134ce10, 0x7f83fc029308, 0xc8212ffc30, 0xc8216669a0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000d540, 0x7f83fc029308, 0xc8212ffc30, 0xc8216669a0)
	/home/matthias/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc82005e8d0, 0x7f83fc029308, 0xc8212ffc30, 0xc8216669a0)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc821372c60, 0x7f83fc029308, 0xc8212ffc30, 0xc8216669a0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8212ffb80)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```
and
```
    "IPAM": {
        "Paxos": null,
        "Range": "[10.32.0.0-10.48.0.0)",
        "DefaultSubnet": "10.32.0.0/12",
        "Entries": [
            {
                "Token": "10.32.0.0",
                "Peer": "4e:22:92:17:ef:4e",
                "Version": 2
            },
            {
                "Token": "10.40.0.0",
                "Peer": "4e:22:92:17:ef:4e",
                "Version": 3
            }
        ],
        "PendingClaims": null,
        "PendingAllocates": [
            "152b2cda83b38cfeb19943213c55c0395d847beed36a7832f5af5d975e08681f"
        ]
    },
```
The entries are the same on both hosts.

And here's the clue as to why it is stuck...
```
$ weave status peers
e6:43:3c:50:d8:34(xps)
   -> 192.168.48.11:6783    82:79:6e:e4:9d:6a(host1)         established
82:79:6e:e4:9d:6a(host1)
   <- 192.168.48.1:33753    e6:43:3c:50:d8:34(xps)           established
```
Note that neither peer has the id of the IPAM entries. So it looks like the `rmpeer` which happens on `reset` doesn't work. @tomwilkie @bboreham

**Comment by bboreham** [comment]
The `rmpeer` attempts to give the space away to another peer.  If this is the only peer running, that attempt will fail.  So this is behaving as expected.

**Comment by bboreham** [comment]
Ah, I think you meant at the time of the `weave reset` there were two peers running.  So more thought required.

**Comment by rade** [comment]
So here's what is happening...

0. we have an IPAM ring with half belonging to peer A and half to peer B.
1. peer A is reset. It transfers its entries to the remaining peer B. Now everything belongs to B.
2. peer A starts again, getting a new identity A'. A' learns the IPAM entries ("everything belongs to B") through gossip from B. Nothing changes in the IPAM entries, since there are no allocation requests at A' (or B).
3. peer B is reset. It finds no peer to transfer its entries to.
4. peer B starts again, getting a new identity B'. B' learns the IPAM entries ("everything belongs to B") through gossip from A'. Nothing changes in the IPAM entries, since there are no allocation requests at A' (or B').
5. an allocation request is made at A'. The peer discovers that the entire ring belongs to B. It attempts to communicate with B, which it can't (B is long dead). So it just sits their waiting for happier days.

The problem is step 3. The transfer logic only picks a peer from those mentioned in IPAM entries. Which only includes peers which have made an allocation.

**Comment by rade** [comment]
@bboreham reckons this problem was masked pre 1.1.0 since there `weave launch` would require an IP allocation for weaveDNS.

**Comment by 3cham** [comment]
Hi, I still have this problem with weave 1.8.0 on CentOS.

Reprodu
On a new start of each Host, weave is started through systemctl like following:
```
ExecStartPre=/usr/local/bin/weave reset 
ExecStartPre=/usr/local/bin/weave launch --ipalloc-range 192.168.0.0/24 --init-peer-count 4
and for second host: (ExecStartPre=/usr/local/bin/weave launch --ipalloc-range 192.168.0.0/24 --init-peer-count 4 firsthost)
ExecStart=/usr/bin/docker attach weave
ExecStop=/usr/local/bin/weave stop
```
After that, any effort starting container doesnt succeed, weave run hang. Following is weave report:

```json
{
    "Version": "1.8.0",
    "VersionCheck": {
        "Enabled": true,
        "NewVersion": "1.8.2",
        "NextCheckAt": "2016-12-15T21:08:38.139610926Z"
    },
    "Router": {
        "Protocol": "weave",
        "ProtocolMinVersion": 1,
        "ProtocolMaxVersion": 2,
        "Encryption": false,
        "PeerDiscovery": true,
        "Name": "fe:a6:38:96:1d:82",
        "NickName": "host02",
        "Port": 6783,
        "Peers": [
            {
                "Name": "fe:a6:38:96:1d:82",
                "NickName": "host02",
                "UID": 3779797580419426406,
                "ShortID": 1338,
                "Version": 5,
                "Connections": [
                    {
                        "Name": "ea:ee:10:55:64:59",
                        "NickName": "host03",
                        "Address": "10.32.104.64:59884",
                        "Outbound": false,
                        "Established": true
                    }
                ]
            },
            {
                "Name": "ea:ee:10:55:64:59",
                "NickName": "host03",
                "UID": 14381165401992208244,
                "ShortID": 522,
                "Version": 2,
                "Connections": [
                    {
                        "Name": "fe:a6:38:96:1d:82",
                        "NickName": "host02",
                        "Address": "10.32.104.63:6783",
                        "Outbound": true,
                        "Established": true
                    }
                ]
            }
        ],
        "UnicastRoutes": [
            {
                "Dest": "fe:a6:38:96:1d:82",
                "Via": "00:00:00:00:00:00"
            },
            {
                "Dest": "ea:ee:10:55:64:59",
                "Via": "ea:ee:10:55:64:59"
            }
        ],
        "BroadcastRoutes": [
            {
                "Source": "fe:a6:38:96:1d:82",
                "Via": [
                    "ea:ee:10:55:64:59"
                ]
            },
            {
                "Source": "ea:ee:10:55:64:59",
                "Via": null
            }
        ],
        "Connections": [
            {
                "Address": "10.32.104.64:59884",
                "Outbound": false,
                "State": "established",
                "Info": "fastdp ea:ee:10:55:64:59(host03)"
            }
        ],
        "TerminationCount": 1,
        "Targets": null,
        "OverlayDiagnostics": {
            "fastdp": {
                "Vports": [
                    {
                        "ID": 0,
                        "Name": "datapath",
                        "TypeName": "internal"
                    },
                    {
                        "ID": 1,
                        "Name": "vethwe-datapath",
                        "TypeName": "netdev"
                    },
                    {
                        "ID": 2,
                        "Name": "vxlan-6784",
                        "TypeName": "vxlan"
                    }
                ],
                "Flows": []
            },
            "sleeve": null
        },
        "TrustedSubnets": [],
        "Interface": "datapath (via ODP)",
        "CaptureStats": {
            "FlowMisses": 195
        },
        "MACs": null
    },
    "IPAM": {
        "Paxos": {
            "Elector": true,
            "KnownNodes": 2,
            "Quorum": 3
        },
        "Range": "192.168.0.0/24",
        "RangeNumIPs": 256,
        "ActiveIPs": 0,
        "DefaultSubnet": "192.168.0.0/24",
        "Entries": null,
        "PendingClaims": null,
        "PendingAllocates": null
    },
    "DNS": {
        "Domain": "weave.local.",
        "Upstream": [
            "10.79.255.100",
            "10.79.255.200"
        ],
        "Address": "172.17.0.1:53",
        "TTL": 1,
        "Entries": null
    }
}
``` 
Could anyone please help me?

**Comment by bboreham** [comment]
@3cham it's better if you create a new issue for your unique symptoms.

You start with `--init-peer-count 4`

This results in:

            "KnownNodes": 2,
            "Quorum": 3

How many Weave Net peers did you start?

**Comment by 3cham** [comment]
@bboreham I intended to have only two peers, however forgot to change the parameter back to 2. Could it be the reason here? I will change this parameter and let you know.

**Comment by bboreham** [comment]
@3cham yes, definitely.  See https://www.weave.works/docs/net/2537-fix-status-on-version-check-failures/ipam/#quorum for some background info.

**Comment by 3cham** [comment]
@bboreham yes, that was the exact reason. Thank you for your prompt support. (y)
