### ISSUE TITLE
periodic panic: Not sorted! running 1.2

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1603]
```
panic: Not sorted!

goroutine 222 [running]:
github.com/weaveworks/weave/nameserver.checkAndPanic(0x7fdaf108e090, 0xc821bd0680)
	/home/bryan/golang/src/github.com/weaveworks/weave/nameserver/entry.go:117 +0x6d
github.com/weaveworks/weave/nameserver.(*GossipData).Encode(0xc82183d620, 0x0, 0x0, 0x0)
	/home/bryan/golang/src/github.com/weaveworks/weave/nameserver/entry.go:246 +0xc7
github.com/weaveworks/weave/router.(*GossipChannel).sendDown.func1(0x7fdaf1915510, 0xc82183d620)
	/home/bryan/golang/src/github.com/weaveworks/weave/router/gossip_channel.go:159 +0x69
github.com/weaveworks/weave/router.(*GossipSender).run(0xc8218dbd40)
	/home/bryan/golang/src/github.com/weaveworks/weave/router/gossip.go:61 +0xf1
created by github.com/weaveworks/weave/router.NewGossipSender
	/home/bryan/golang/src/github.com/weaveworks/weave/router/gossip.go:50 +0xf3
```

**Comment by bboreham** [comment]
More detail on this issue:

- When periodic gossip arrives, if it contains data which is new to us, we attempt to pass on that data to other peers.  However, the new data was being returned sorted case-insensitive, which caused a panic because data on the wire is supposed to be sent case-sensitive.
