### ISSUE TITLE
panic in net.forEachRoute when starting container via proxy

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1909]
````
$ eval $(weave env)
$ docker run --name=foo -ti ubuntu
root@foo:/# exit
exit
$ docker run --name=foo1 --hostname=foo.weave.local -ti ubuntu
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x458102]

goroutine 1 [running]:
github.com/weaveworks/weave/net.forEachRoute(0xc8200a00f0, 0xc820039be8, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/net/route.go:49 +0x232
github.com/weaveworks/weave/net.CheckRouteExists(0x55c068, 0x5, 0xc820039c68, 0x10, 0x10, 0x0)
	/go/src/github.com/weaveworks/weave/net/route.go:63 +0xa8
github.com/weaveworks/weave/net.EnsureInterfaceAndMcastRoute(0x55c068, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/net/if.go:56 +0x338
main.checkNetwork(0x0, 0x0)
	/go/src/github.com/weaveworks/weave/prog/weavewait/check_network_iface_mcast.go:10 +0x38
main.main()
	/go/src/github.com/weaveworks/weave/prog/weavewait/main.go:20 +0x6b

goroutine 6 [chan send]:
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.LinkSubscribe.func2(0xc820014120, 0xc82000a0e0)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:847 +0x2e6
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.LinkSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:850 +0x107

goroutine 17 [runnable]:
syscall.Syscall(0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x4, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Close(0xc82009e220)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:325 +0x24
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe.func1(0xc8200b6060, 0xc82009e220)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:306 +0x44
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:307 +0xe6

goroutine 18 [runnable]:
syscall.Syscall6(0x2d, 0x4, 0xc8200ca000, 0x1000, 0x0, 0xc82001ec48, 0xc82001ec44, 0x6c, 0x1000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x4, 0xc8200ca000, 0x1000, 0x1000, 0x0, 0xc82001ec48, 0xc82001ec44, 0x40e819, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x91
syscall.Recvfrom(0x4, 0xc8200ca000, 0x1000, 0x1000, 0x0, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:244 +0xb8
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc82009e220, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:341 +0xae
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe.func2(0xc8200b6000, 0xc82009e220)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:312 +0x61
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:324 +0x115
Error response from daemon: Failure during network configuration for container 08f8447ca51cf71a1c6ec5b0612fdc4212bc977740dcda0522fd30accd24204c:
nsenter: cannot open /hostproc/15566/ns/net: No such file or directory
```

I got this once and have not been able to reproduce it since.

Might be related to #1898, though I am running a 3.19 kernel.

**Comment by rade** [comment]
To reproduce, apply
```patch
diff --git a/net/route.go b/net/route.go
index 3424826..988a7d7 100644
--- a/net/route.go
+++ b/net/route.go
@@ -3,6 +3,7 @@ package net
 import (
        "fmt"
        "net"
+       "time"
 
        "github.com/vishvananda/netlink"
 )
@@ -39,6 +40,7 @@ func forEachRoute(ignoreIfaceNames map[string]struct{}, check 
        if err != nil {
                return err
        }
+       time.Sleep(1 * time.Minute)
        for _, route := range routes {
                link, err := netlink.LinkByIndex(route.LinkIndex)
                if err == nil {
```

rebuild weave, and then
```
$ weave launch
(this will take ~1 minute due to the above patch)
$ eval $(weave env)
$ docker run --name=foo -ti ubuntu
...
in another window...
$ sudo bin/docker-ns foo ip link del ethwe
```

ATM I cannot think of a way for this bug to occur that doesn't involve some interface going away. Which, while possible in general, should not have happened in the scenario where I encountered the problem. So there may well be another issue here.

**Comment by rade** [comment]
I've just run into this again. The proxy logs contain
```
INFO: 2016/01/19 14:11:37.257649 Attaching container cb0e24a3cf39fa3788a73b2ea20a3f1a6ae1118a4462d477988de152b9798e3a with WEAVE_CIDR "" to weave network
WARN: 2016/01/19 14:11:37.979612 Attaching container cb0e24a3cf39fa3788a73b2ea20a3f1a6ae1118a4462d477988de152b9798e3a to weave network failed: Failure during network configuration for container cb0e24a3cf39fa3788a73b2ea20a3f1a6ae1118a4462d477988de152b9798e3a:
nsenter: cannot open /hostproc/13221/ns/net: No such file or directory
nsenter: cannot open /hostproc/13221/ns/net: No such file or directory
```
The container logs only have the stacktrace.

I've also had another failure, this time with just one `nsenter` complaint.

**Comment by rade** [comment]
Further investigation shows that `CheckRoute` is tripping over the route `{Ifindex: 343 Dst: 172.17.0.0/16 Src: 172.17.0.4 Gw: <nil> Flags: []}`, returning `Link not Found` from `netlink.LinkByIndex`. The ifindex corresponds to eth0, which *does* exist:
```
$ sudo bin/docker-ns 29ec ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
343: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff
345: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 3e:f7:a1:b7:2e:89 brd ff:ff:ff:ff:ff:ff
```
So it really looks like `netlink.LinkByIndex` is lying.
