### ISSUE TITLE
Crash in /w/w

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1932]
Not super important, as I'm hacking on proxy/cni integrations, but I hit this.  We should handle more gracefully.

```
Toms-MacBook-Pro:weave twilkie$ docker logs high_brattain
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x458020]

goroutine 1 [running]:
github.com/weaveworks/weave/net.EnsureInterfaceAndMcastRoute.func1(0xdd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc82008b028, 0x4, 0xfd8, ...)
	/go/src/github.com/weaveworks/weave/net/if.go:56 +0x30
github.com/weaveworks/weave/net.EnsureInterfaceAndMcastRoute(0x55bc08, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/net/if.go:69 +0x5ae
main.checkNetwork(0x0, 0x0)
	/go/src/github.com/weaveworks/weave/prog/weavewait/check_network_iface_mcast.go:10 +0x38
main.main()
	/go/src/github.com/weaveworks/weave/prog/weavewait/main.go:20 +0x6b

goroutine 6 [chan send]:
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.LinkSubscribe.func2(0xc820014120, 0xc82000a0e0)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:847 +0x2e6
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.LinkSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:850 +0x107

goroutine 7 [runnable]:
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe.func1(0xc820014240, 0xc82000a540)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:305 +0x36
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:307 +0xe6

goroutine 8 [syscall]:
syscall.Syscall6(0x2d, 0x4, 0xc82008c000, 0x1000, 0x0, 0xc82003bc38, 0xc82003bc34, 0x4, 0xfd0, 0xc820070800)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x4, 0xc82008c000, 0x1000, 0x1000, 0x0, 0xc82003bc38, 0xc82003bc34, 0x40e819, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x91
syscall.Recvfrom(0x4, 0xc82008c000, 0x1000, 0x1000, 0x0, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:244 +0xb8
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc82000a540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:341 +0xae
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe.func2(0xc8200141e0, 0xc82000a540)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:312 +0x61
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.RouteSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/route_linux.go:324 +0x115
```

**Comment by tomwilkie** [comment]
```diff
diff --git a/net/if.go b/net/if.go
index dc391b8..ebc4bc6 100644
--- a/net/if.go
+++ b/net/if.go
@@ -53,6 +53,9 @@ func EnsureInterfaceAndMcastRoute(ifaceName string) (*net.Interface, error) {
        }
        dest := net.IPv4(224, 0, 0, 0)
        check := func(route netlink.Route) bool {
+               fmt.Println(route)
+               fmt.Println("route.Dst == nil?", route.Dst == nil)
+               fmt.Println("route.Dst.IP == nil?", route.Dst.IP == nil)
                return route.LinkIndex == iface.Index && route.Dst.IP.Equal(dest)
        }
        // check for currently-existing route after subscribing, to avoid race
```

I get:

```
Toms-MacBook-Pro:weave twilkie$ docker run --rm -ti -l cni.network=net1 alpine ifconfig
{Ifindex: 287 Dst: <nil> Src: <nil> Gw: 172.17.0.1 Flags: []}
route.Dst == nil? true
```

**Comment by tomwilkie** [comment]
```shell
Toms-MacBook-Pro:weave twilkie$ docker run --rm -ti -l cni.network=net1 alpine /bin/sh
/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.17.0.1      0.0.0.0         UG    0      0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 eth0
```

**Comment by rade** [comment]
Allegedly the interface and routing tables look like this:
```
Toms-MacBook-Pro:weave twilkie$ docker run --rm -ti -l cni.network=net1 alpine /bin/sh
/ # ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2%32609/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:518 (518.0 B)  TX bytes:418 (418.0 B)
​
ethwe     Link encap:Ethernet  HWaddr 5E:6D:A4:F4:8D:93  
          inet addr:192.168.0.9  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::5c6d:a4ff:fef4:8d93%32609/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:298 (298.0 B)  TX bytes:418 (418.0 B)
​
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%32609/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
​
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.32.0.12      0.0.0.0         UG    0      0        0 ethwe
10.32.0.12      0.0.0.0         255.255.255.255 UH    0      0        0 ethwe
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
```

Note that there is no route entry corresponding to the one weave is tripping over. @tom says that it is quite possible that route entries are being changed dynamically, so it may be tripping over a temp entry.

**Comment by rade** [comment]
Note that this issue was present even pre #1910.
