### ISSUE TITLE
Weave router will crash without Docker API connection

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2421]
There is code in `main.go` to allow a blank path, but if you try to use it the next section of code crashes:

````
$ docker run --net=host -i weaveworks/weave --name 00:00:00:00:00:00 --docker-api=""
INFO: 2016/07/05 11:53:27.128082 Command line options: map[docker-api: name:00:00:00:00:00:00]
INFO: 2016/07/05 11:53:27.128176 Communication between peers is unencrypted.
INFO: 2016/07/05 11:53:27.157018 Our name is 00:00:00:00:00:00(bryan-work)
INFO: 2016/07/05 11:53:27.157241 Launch detected - using supplied peer list: []
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x623c58]

goroutine 1 [running]:
github.com/weaveworks/weave/common/docker.(*Client).DockerVersion(0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/common/docker/client.go:88 +0x28
main.main()
	/go/src/github.com/weaveworks/weave/prog/weaver/main.go:269 +0x27de
````

**Comment by bboreham** [comment]
Fixed in e5c23bf9f542e24b8fd757981e71367d2a1a65af
