### ISSUE TITLE
Router could not start due to invalid expected type (odp.TunnelFlowKey)

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2488]
Happened after rebooting a host machine and checking `docker logs weave` output multiple times (after ~100th iteration).

Weave: 1.6.0 (restarted by Docker)
Docker: 1.10.3
Host: VBox VM, CoreOS, 4.6.3 Kernel

```
INFO: 2016/08/25 18:10:05.771551 Command line options: map[dns-effective-listen-address:172.18.0.1 dns-listen-address:172.18.0.1:53 http-addr:127.0.0.1:6784 name:7e:da:f1:fa:89:7e resolv-conf:/var/run/weave/etc/resolv.conf datapath:datapath ipalloc-range:10.32.0.0/12 nickname:core-01 port:6783]
INFO: 2016/08/25 18:10:05.937167 Communication between peers is unencrypted.
INFO: 2016/08/25 18:10:05.959241 Our name is 7e:da:f1:fa:89:7e(core-01)
INFO: 2016/08/25 18:10:05.959384 Restart/resume detected - using persisted peer list: []
INFO: 2016/08/25 18:10:05.971369 Docker API on unix:///var/run/docker.sock: &[Arch=amd64 KernelVersion=4.6.3-coreos Version=1.10.3 ApiVersion=1.22 GitCommit=3cd164c GoVersion=go1.5.4 Os=linux]
INFO: 2016/08/25 18:10:05.973637 [allocator 7e:da:f1:fa:89:7e] Initialising with persisted data
INFO: 2016/08/25 18:10:05.975435 Listening for DNS queries on 172.18.0.1
INFO: 2016/08/25 18:10:05.975457 Sniffing traffic on datapath (via ODP)
INFO: 2016/08/25 18:10:05.999255 Listening for HTTP control messages on 127.0.0.1:6784
panic: interface conversion: interface is nil, not odp.TunnelFlowKey

goroutine 19 [running]:
github.com/weaveworks/weave/router.(*FastDatapath).getVxlanVportID.func1(0xc8213ed200, 0xc8213f0ce0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/router/fastdp.go:427 +0xd7
github.com/weaveworks/weave/router.(*FastDatapath).Miss(0xc82007a360, 0xc8213f4ca4, 0x14c, 0x153, 0xc8213ed200, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/router/fastdp.go:959 +0x4fd
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.DatapathHandle.consumeMisses.func1(0xc8213f0b60, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/packet.go:144 +0x230
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).consume.func1(0xc8213f0b60, 0xc8213f0b60, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:683 +0x17a
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).Receive(0xc8212a9260, 0xc82150fef0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:589 +0x107
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).consume(0xc8212a9260, 0x7f6fd93d9028, 0xc82007a360, 0xc82150ff58)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:680 +0x57
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.DatapathHandle.consumeMisses(0xc8212aeaf0, 0x5, 0x7f6fd9423ee0, 0xc82007a360, 0xc8212aeb40)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/packet.go:145 +0xa3
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.DatapathHandle.ConsumeMisses
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/packet.go:74 +0x5c4

goroutine 1 [chan receive]:
github.com/weaveworks/weave/common.SignalHandlerLoop(0xc8212a1c78, 0x1, 0x1)
        /go/src/github.com/weaveworks/weave/common/signals.go:20 +0x2e8
main.main()
        /go/src/github.com/weaveworks/weave/prog/weaver/main.go:340 +0x362f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 36 [IO wait]:
net.runtime_pollWait(0x7f6fd9425480, 0x72, 0xc820010090)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200c86f0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200c86f0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readMsg(0xc8200c8690, 0xc8212dd200, 0x200, 0x200, 0xc821369770, 0x28, 0x28, 0xffffffffffffffff, 0x0, 0x0, ...)
        /usr/local/go/src/net/fd_unix.go:286 +0x33d
net.(*UDPConn).ReadMsgUDP(0xc821378020, 0xc8212dd200, 0x200, 0x200, 0xc821369770, 0x28, 0x28, 0x200, 0xbca120, 0x1, ...)
        /usr/local/go/src/net/udpsock_posix.go:96 +0x171
github.com/weaveworks/weave/vendor/github.com/miekg/dns.ReadFromSessionUDP(0xc821378020, 0xc8212dd200, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/udp.go:47 +0xc1
github.com/weaveworks/weave/vendor/github.com/miekg/dns.(*Server).readUDP(0xc82005c4e0, 0xc821378020, 0x77359400, 0x0, 0x0, 0x0, 0xea01c0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/server.go:646 +0x190
github.com/weaveworks/weave/vendor/github.com/miekg/dns.(*defaultReader).ReadUDP(0xc8200246f8, 0xc821378020, 0x77359400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/server.go:253 +0x5f
github.com/weaveworks/weave/vendor/github.com/miekg/dns.(*Server).serveUDP(0xc82005c4e0, 0xc821378020, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/server.go:519 +0x207
github.com/weaveworks/weave/vendor/github.com/miekg/dns.(*Server).ActivateAndServe(0xc82005c4e0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/server.go:397 +0x23c
github.com/weaveworks/weave/nameserver.(*DNSServer).ActivateAndServe.func1(0xc82005c4e0)
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:141 +0x21
created by github.com/weaveworks/weave/nameserver.(*DNSServer).ActivateAndServe
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:142 +0x7b

goroutine 37 [IO wait]:
net.runtime_pollWait(0x7f6fd94253c0, 0x72, 0xc820010090)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200c8760, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200c8760, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200c8700, 0x0, 0x7f6fd93dd650, 0xc8212cd6a0)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc821378028, 0x41c61d, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc821378028, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/weaveworks/weave/vendor/github.com/miekg/dns.(*Server).serveTCP(0xc82005c5b0, 0x7f6fd93d94b8, 0xc821378028, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/server.go:476 +0x1dd
github.com/weaveworks/weave/vendor/github.com/miekg/dns.(*Server).ActivateAndServe(0xc82005c5b0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/server.go:405 +0x306
github.com/weaveworks/weave/nameserver.(*DNSServer).ActivateAndServe.func1(0xc82005c5b0)
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:141 +0x21
created by github.com/weaveworks/weave/nameserver.(*DNSServer).ActivateAndServe
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:142 +0x7b

goroutine 35 [select]:
github.com/weaveworks/weave/nameserver.(*Nameserver).Start.func1(0xc8200c8540)
        /go/src/github.com/weaveworks/weave/nameserver/nameserver.go:62 +0xfe
created by github.com/weaveworks/weave/nameserver.(*Nameserver).Start
        /go/src/github.com/weaveworks/weave/nameserver/nameserver.go:69 +0x35

goroutine 34 [chan receive]:
github.com/weaveworks/weave/common/docker.(*Client).AddObserver.func1(0xc8200243d0, 0x7f6fd93d9538, 0xc8200c8540)
        /go/src/github.com/weaveworks/weave/common/docker/client.go:107 +0x3af
created by github.com/weaveworks/weave/common/docker.(*Client).AddObserver
        /go/src/github.com/weaveworks/weave/common/docker/client.go:131 +0x55

goroutine 16 [chan send]:
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.LinkSubscribe.func2(0xc820016780, 0xc8212a6620)
        /go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:898 +0x2db
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.LinkSubscribe
        /go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:901 +0x107

goroutine 18 [syscall]:
syscall.Syscall6(0x2d, 0x7, 0xc821314000, 0x10000, 0x0, 0xc82133bc00, 0xc82133bbfc, 0x20, 0x83d077, 0xc8213f0aa0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x7, 0xc821314000, 0x10000, 0x10000, 0x0, 0xc82133bc00, 0xc82133bbfc, 0x6, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x91
syscall.Recvfrom(0x7, 0xc821314000, 0x10000, 0x10000, 0x0, 0xc800000001, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:244 +0xb8
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).recv(0xc8212a92c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:552 +0x70
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).Receive(0xc8212a92c0, 0xc82133bf08, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:575 +0x3c
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).consume(0xc8212a92c0, 0x7f6fd93d9000, 0xc8212aeb40, 0xc82133bf60)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:680 +0x57
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*Dpif).consumeVportEvents(0xc8212aeb90, 0x7f6fd9423ff0, 0xc8212aeb40, 0x5)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/vport.go:415 +0x9a
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.DatapathHandle.ConsumeVportEvents
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/vport.go:384 +0x1c8

goroutine 20 [syscall]:
syscall.Syscall6(0x2d, 0x8, 0xc821324000, 0x10000, 0x0, 0xc82133ac00, 0xc82133abfc, 0x20, 0x83d077, 0xc8213f0b00)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x8, 0xc821324000, 0x10000, 0x10000, 0x0, 0xc82133ac00, 0xc82133abfc, 0x6, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x91
syscall.Recvfrom(0x8, 0xc821324000, 0x10000, 0x10000, 0x0, 0xc8212a4900, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:244 +0xb8
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).recv(0xc8212a93e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:552 +0x70
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).Receive(0xc8212a93e0, 0xc82133af08, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:575 +0x3c
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*NetlinkSocket).consume(0xc8212a93e0, 0x7f6fd93d9028, 0xc82007a360, 0xc82133af60)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/netlink.go:680 +0x57
github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.(*Dpif).consumeVportEvents(0xc8212aebe0, 0x7f6fd9424050, 0xc82007a360, 0x5)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/vport.go:415 +0x9a
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp.DatapathHandle.ConsumeVportEvents
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/go-odp/odp/vport.go:384 +0x1c8

goroutine 21 [select]:
github.com/weaveworks/weave/router.(*FastDatapath).run(0xc82007a360)
        /go/src/github.com/weaveworks/weave/router/fastdp.go:868 +0x115
created by github.com/weaveworks/weave/router.NewFastDatapath
        /go/src/github.com/weaveworks/weave/router/fastdp.go:140 +0x7e2

goroutine 22 [select]:
github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.(*localPeer).actorLoop(0xc8212a9830, 0xc8200169c0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/local_peer.go:141 +0x102
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.newLocalPeer
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/local_peer.go:31 +0x147

goroutine 23 [select]:
github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.(*routes).run(0xc820079880, 0xc820016b40, 0xc820016ba0, 0xc820016c00)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/routes.go:177 +0x17d
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.newRoutes
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/routes.go:44 +0x496

goroutine 24 [select]:
github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.(*connectionMaker).queryLoop(0xc820016cc0, 0xc820016c60)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/connection_maker.go:221 +0x159
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.newConnectionMaker
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/connection_maker.go:74 +0x24a

goroutine 28 [select]:
github.com/weaveworks/weave/ipam.(*Allocator).actorLoop(0xc82000adc0, 0xc820017980, 0xc8200179e0)
        /go/src/github.com/weaveworks/weave/ipam/allocator.go:673 +0x1b6
created by github.com/weaveworks/weave/ipam.(*Allocator).Start
        /go/src/github.com/weaveworks/weave/ipam/allocator.go:164 +0x173

goroutine 26 [IO wait]:
net.runtime_pollWait(0x7f6fd9425600, 0x72, 0xc820010090)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820049250, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820049250, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200491f0, 0xc82136a000, 0x1000, 0x1000, 0x0, 0x7f6fdad9c028, 0xc820010090)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200243e8, 0xc82136a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f6fd94256c0, 0xc8200243e8, 0xc821281d38, 0xc82136a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc821366420, 0xc82136a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820017260)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820017260, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc821281ce0)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 27 [select]:
net/http.(*persistConn).writeLoop(0xc821281ce0)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 29 [chan receive]:
github.com/weaveworks/weave/common/docker.(*Client).AddObserver.func1(0xc8200243d0, 0x7f6fd9425a68, 0xc82000adc0)
        /go/src/github.com/weaveworks/weave/common/docker/client.go:107 +0x3af
created by github.com/weaveworks/weave/common/docker.(*Client).AddObserver
        /go/src/github.com/weaveworks/weave/common/docker/client.go:131 +0x55

goroutine 30 [select]:
github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xc820016f60, 0xc82007acf0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:202 +0x34f
created by github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
        /go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:169 +0x16c

goroutine 38 [syscall]:
syscall.Syscall6(0x2d, 0xf, 0xc8213c9df9, 0xffff, 0x0, 0xc8213c9b70, 0xc8213c9b6c, 0x0, 0x4203d9, 0xc82005cbb8)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0xf, 0xc8213c9df9, 0xffff, 0xffff, 0x0, 0xc8213c9b70, 0xc8213c9b6c, 0x8c00000000000010, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x91
syscall.Recvfrom(0xf, 0xc8213c9df9, 0xffff, 0xffff, 0x0, 0x7f6fd93dd6b8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:244 +0xb8
net.(*netFD).readFrom(0xc8200c89a0, 0xc8213c9df9, 0xffff, 0xffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:255 +0x1dc
net.(*UDPConn).ReadFromUDP(0xc821378030, 0xc8213c9df9, 0xffff, 0xffff, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:61 +0x117
github.com/weaveworks/weave/router.(*SleeveOverlay).readUDP(0xc8200167e0)
        /go/src/github.com/weaveworks/weave/router/sleeve.go:170 +0x116
created by github.com/weaveworks/weave/router.(*SleeveOverlay).StartConsumingPackets
        /go/src/github.com/weaveworks/weave/router/sleeve.go:124 +0x5fc

goroutine 39 [IO wait]:
net.runtime_pollWait(0x7f6fd9425240, 0x72, 0xc820010090)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200c8a70, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200c8a70, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200c8a10, 0x0, 0x7f6fd93dd650, 0xc8212cd6c0)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc821378040, 0x10f1510, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.(*Router).listenTCP.func1(0xc821378040, 0xc8200a3880)
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/router.go:109 +0x56
created by github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh.(*Router).listenTCP
        /go/src/github.com/weaveworks/weave/vendor/github.com/weaveworks/mesh/router.go:117 +0x23c

goroutine 40 [IO wait]:
net.runtime_pollWait(0x7f6fd9425540, 0x72, 0xc820010090)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc821380a00, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc821380a00, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8213809a0, 0xc821388000, 0x1000, 0x1000, 0x0, 0x7f6fdad9c028, 0xc820010090)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200246e0, 0xc821388000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820017ce0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820017ce0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc820017ce0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc8212cf3b0)
        /usr/local/go/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc8212cf3b0, 0xc8212d6600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc8212d0d40, 0xc8212d6600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc8212d0d40, 0xc8212d6600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:624 +0x110
encoding/json.(*Decoder).refill(0xc82137a9c0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82137a9c0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc82137a9c0, 0xb891a0, 0xc8212d2580, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:57 +0x159
github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*Client).eventHijack.func1(0xc8211012f0, 0xc82007acf0, 0xc820017c20, 0xc820017c80, 0xc82007b0e0, 0xc8213820b0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:311 +0x192
created by github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*Client).eventHijack
        /go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:330 +0x6c4

goroutine 41 [IO wait]:
net.runtime_pollWait(0x7f6fd9425180, 0x72, 0xc820010090)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8213f87d0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8213f87d0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8213f8770, 0x0, 0x7f6fd93dd650, 0xc8213f08c0)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8213782f0, 0x4625b0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8213782f0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8213eade0, 0x7f6fd93d94b8, 0xc8213782f0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7f6fd93d94b8, 0xc8213782f0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1765 +0x85
main.listenAndServeHTTP(0x7ffe8f08bf3a, 0xe)
        /go/src/github.com/weaveworks/weave/prog/weaver/main.go:563 +0x2f5
created by main.main
        /go/src/github.com/weaveworks/weave/prog/weaver/main.go:337 +0x354e

goroutine 42 [select, locked to thread]:
runtime.gopark(0x10f1b40, 0xc821362f28, 0xf05ad0, 0x6, 0x43dd18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc821362f28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc821362f28)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by brb** [comment]
This happens because `OVS_KEY_ATTR_TUNNEL` is missing in `FlowKeys`.

**Comment by awh** [comment]
@brb do we know _why_ it's missing?

**Comment by brb** [comment]
My hypothesis is that `tun_proto` (which lack results in missing `OVS_KEY_ATTR_TUNNEL`) gets set in the kernel after vport becomes available, so the race 1) create vport 2) miss 3) set vport params could explain the issue. However, I haven't had enough time to prove it.
