### ISSUE TITLE
Docker restart seems to leave weave in unrecoverable state

### ISSUE THREAD

**Issue by cwolfinger** [weaveworks/weave#2536]
Using weave 1.6.2 with Docker 1.12.1, I noticed the following logs in the weave docker logs:

```
ERRO: 2016/10/03 17:05:21.023246 [docker] Event listener channel closed - retrying subscription in 20s
ERRO: 2016/10/03 17:05:41.334719 [docker] Event listener channel closed - retrying subscription in 20s
```

These log messages had been occurring for some time.  These log messages started at:

`ERRO: 2016/10/02 04:12:31.682715 [docker] Event listener channel closed - retrying subscription in 1s`

In the docker logs I see a crash and a restart - we are running with live restore for starting Docker:

```
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: [signal 0xb code=0x1 addr=0x0 pc=0x474cc5]
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: goroutine 46113090 [running]:
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: panic(0x1ab2e40, 0xc82000e090)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: bytes.(*Buffer).grow(0xc821587800, 0x13d, 0xc82085c2a0)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/local/go/src/bytes/buffer.go:107 +0x32a
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: bytes.(*Buffer).Write(0xc821587800, 0xc822012000, 0x13d, 0x8000, 0x7d, 0x0, 0x0)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/local/go/src/bytes/buffer.go:134 +0x4b
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: github.com/docker/docker/daemon.(*limitedBuffer).Write(0xc821587800, 0xc822012000, 0x13d, 0x8000, 0x13d, 0x0, 0x0)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/health.go:283 +0xae
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: io.copyBuffer(0x7f9ffc02f2f8, 0xc821587800, 0x7fa0088a6fc8, 0xc82202fa00, 0xc822012000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/local/go/src/io/io.go:382 +0x2c9
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: io.Copy(0x7f9ffc02f2f8, 0xc821587800, 0x7fa0088a6fc8, 0xc82202fa00, 0xc82202fa00, 0x0, 0x0)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/local/go/src/io/io.go:350 +0x64
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: github.com/docker/docker/container.AttachStreams.func2(0x1d9de28, 0x6, 0x7f9ffc02f2f8, 0xc821587800, 0x7fa0088a6f98, 0xc82202fa00)
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:433 +0x1cc
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]: created by github.com/docker/docker/container.AttachStreams
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 docker[26077]:         /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:451 +0x3e0
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 systemd[1]: docker.service: Unit entered failed state.
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 systemd[1]: docker.service: Failed with result 'exit-code'.
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 systemd[1]: Stopped Docker Application Container Engine.
Oct 02 04:12:31 do-er-46dngcm3nz53-0-xz2udwzoqqrl-worker-dpw7nb74gv43 systemd[1]: Starting Docker Application Container Engine...

```
Once docker restarts the weave can no longer attach to the socket.  Is this expected behavior?

**Comment by bboreham** [comment]
Speculating this is because the docker socket was bind-mounted and we don't have any code to re-mount the new socket. 

With the old behaviour all containers died when the docker daemon died so this didn't matter.

**Comment by rade** [comment]
Isn't that stack trace from Docker rather than Weave Net?

**Comment by bboreham** [comment]
Yes. The context is a Docker crash and restart with "[live restore](https://docs.docker.com/engine/admin/live-restore/)", i.e. containers keep running.

**Comment by cwolfinger** [comment]
Correct - it appears that since the container is still running it tries to reconnect to the original socket and not the new socket.  We may turn off live restore just to stop this behavior.

**Comment by bboreham** [comment]
I have recreated this issue, simply by enabling Live Restore then restarting Docker.

**Comment by cwolfinger** [comment]
So would using the "plugin" approach for docker work better ?  We defaulted on a new project to use the proxy since it was more transparent on what was really going on behind the scenes - but I was curious as to where the "future" of weave will be - the plugin or the proxy for docker networking.

**Comment by bboreham** [comment]
@cwolfinger the Weave Net Docker Network Plugin also wants to talk to Docker on its socket, so will also be degraded.  

Actually, I'm interested in what actually went wrong for you, aside from the log messages.  I tried both, and was still able to create containers and connect them to the Weave Network.  I believe WeaveDNS will stop updating in the proxy case, and we will be unable to optimise various network settings inside the container in the plugin case.

The future of Weave Net is that we will support both the proxy mechanism and the Docker Plugin mechanism.  The proxy allows us to make things easier for the user, and the plugin allows us to be compatible with Docker's standards.

At this point in time Weave Net is incompatible with Docker Live Restore.

**Comment by cwolfinger** [comment]
Hi - the issue we had was that the DNS did not refresh.  It was stuck and all the "dead" nodes were still shown to be in Weave DNS.

**Comment by brb** [comment]
Another user tripped over it: https://weave-community.slack.com/archives/C2ND76PAA/p1490695149883727
