### ISSUE TITLE
Weave launch hangs in minikube VM

### ISSUE THREAD

**Issue by leth** [weaveworks/weave#3228]
## What happened?
Weave launch hangs at startup

## How to reproduce it?
Enter minikube VM (minikube ssh)
download + chmod weave
weave launch

## Anything else we need to know?
Minikube version v0.23.6

## Versions:
```
$ weave version
weave script 2.1.3
weave 2.1.3
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ uname -a
Linux minikube 4.9.13 #1 SMP Thu Oct 19 17:14:00 UTC 2017 x86_64 GNU/Linux
```

## Logs:
```
INFO: 2018/01/29 11:55:10.465488 Command line options: map[ipalloc-range:10.32.0.0/12 tlscacert:/home/weave/tls/ca.pem weave-bridge:weave datapath:datapath H:[unix:///var/run/weave/weave.sock] docker-bridge:docker0 nickname:minikube resolv-conf:/var/run/weave/etc/resolv.conf tlscert:/home/weave/tls/cert.pem tlskey:/home/weave/tls/key.pem dns-effective-listen-address:172.17.0.1 dns-listen-address:172.17.0.1:53 port:6783 tlsverify:true host-root:/host plugin:true status-addr:127.0.0.1:6782 token:<redacted> http-addr:127.0.0.1:6784 proxy:true]
INFO: 2018/01/29 11:55:10.465575 weave  2.1.3
INFO: 2018/01/29 11:55:10.467712 Docker API on unix:///var/run/docker.sock: &[Version=17.06.0-ce GoVersion=go1.8.3 Arch=amd64 KernelVersion=4.9.13 ApiVersion=1.30 MinAPIVersion=1.12 GitCommit=02c1d87 Os=linux BuildTime=2017-06-23T21:51:55.152028673+00:00]
INFO: 2018/01/29 11:55:10.467914 Using docker bridge IP for DNS: 172.17.0.1
INFO: 2018/01/29 11:55:10.472081 proxy listening on unix:///var/run/weave/weave.sock
INFO: 2018/01/29 11:55:10.481939 Bridge type is bridge
INFO: 2018/01/29 11:55:10.481966 Communication between peers is unencrypted.
SIGQUIT: quit
PC=0x45d051 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x15b65b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffdd9b1f310, 0x4100bb, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:422 +0x21
runtime.futexsleep(0x15b65b0, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x15b65b0)
	/usr/local/go/src/runtime/lock_futex.go:145 +0x6b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc42001a000, 0x0)
	/usr/local/go/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2222 +0x14c
runtime.park_m(0xc42038f380)
	/usr/local/go/src/runtime/proc.go:2285 +0xab
runtime.mcall(0x7ffdd9b1f4a0)
	/usr/local/go/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [chan receive, 106 minutes]:
github.com/weaveworks/weave/net.ensureInterface(0xe5cfcf, 0xb, 0xd8a020, 0x1, 0xc4203289f0)
	/go/src/github.com/weaveworks/weave/net/if.go:32 +0xeb
github.com/weaveworks/weave/net.EnsureInterface(0xe5cfcf, 0xb, 0xc4203289c0, 0x0, 0xc4203289c0)
	/go/src/github.com/weaveworks/weave/net/if.go:13 +0x35
main.createOverlay(0x158c480, 0xc420320ae0, 0x7ffdd9b20d8f, 0x7, 0x7ffdd9b20da6, 0x5, 0x7ffdd9b20db7, 0x8, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/weave/prog/weaver/main.go:580 +0x311
main.main()
	/go/src/github.com/weaveworks/weave/prog/weaver/main.go:302 +0x27db

goroutine 17 [syscall, 106 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall, 106 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 42 [select]:
github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xc42005db00, 0xc4201b6280)
	/go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:209 +0x36a
created by github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
	/go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:176 +0x146

goroutine 38 [chan receive, 102 minutes]:
github.com/weaveworks/weave/common/docker.(*Client).AddObserver.func1(0xc42000e348, 0x1588580, 0xc420075080)
	/go/src/github.com/weaveworks/weave/common/docker/client.go:107 +0x2bc
created by github.com/weaveworks/weave/common/docker.(*Client).AddObserver
	/go/src/github.com/weaveworks/weave/common/docker/client.go:131 +0x53

goroutine 43 [chan receive, 106 minutes]:
github.com/weaveworks/weave/proxy.(*Proxy).Serve(0xc420075080, 0xc420295070, 0x1, 0x1, 0xc420320a20)
	/go/src/github.com/weaveworks/weave/proxy/proxy.go:305 +0x10d
created by main.main
	/go/src/github.com/weaveworks/weave/prog/weaver/main.go:277 +0x24b7

goroutine 30 [runnable]:
reflect.(*rtype).ptrTo(0xcb96c0, 0xc4204b76d0)
	/usr/local/go/src/reflect/type.go:1428 +0x570
reflect.Value.Addr(0xcb96c0, 0xc4200614b8, 0x198, 0x1593de0, 0xcb96c0, 0xc42017a929)
	/usr/local/go/src/reflect/value.go:241 +0x3c
encoding/json.(*decodeState).indirect(0xc42012fc28, 0xcb96c0, 0xc4200614b8, 0x198, 0x150e46264bea8a00, 0x0, 0x0, 0x0, 0x0, 0xcb9040, ...)
	/usr/local/go/src/encoding/json/decode.go:444 +0x5e5
encoding/json.(*decodeState).literalStore(0xc42012fc28, 0xc42017a60b, 0x6, 0x5f5, 0xcb96c0, 0xc4200614b8, 0x198, 0xc49f00)
	/usr/local/go/src/encoding/json/decode.go:830 +0x1fa
encoding/json.(*decodeState).literal(0xc42012fc28, 0xcb96c0, 0xc4200614b8, 0x198)
	/usr/local/go/src/encoding/json/decode.go:799 +0xdf
encoding/json.(*decodeState).value(0xc42012fc28, 0xcb96c0, 0xc4200614b8, 0x198)
	/usr/local/go/src/encoding/json/decode.go:405 +0x32e
encoding/json.(*decodeState).object(0xc42012fc28, 0xc8ae00, 0xc420061480, 0x16)
	/usr/local/go/src/encoding/json/decode.go:733 +0x12d8
encoding/json.(*decodeState).value(0xc42012fc28, 0xc8ae00, 0xc420061480, 0x16)
	/usr/local/go/src/encoding/json/decode.go:402 +0x2f4
encoding/json.(*decodeState).unmarshal(0xc42012fc28, 0xc8ae00, 0xc420061480, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:184 +0x21a
encoding/json.(*Decoder).Decode(0xc42012fc00, 0xc8ae00, 0xc420061480, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:67 +0x1c3
github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*Client).eventHijack.func1(0xc4202952a0, 0xc4201b6280, 0xc42025d6e0, 0xc42025d740, 0xc4200d0cf0, 0xc42008b550)
	/go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:330 +0x136
created by github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient.(*Client).eventHijack
	/go/src/github.com/weaveworks/weave/vendor/github.com/fsouza/go-dockerclient/event.go:351 +0x413

goroutine 168 [IO wait, 106 minutes]:
net.runtime_pollWait(0x7f4addb68340, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201b5418, 0x72, 0x0, 0xc4204becc0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201b5418, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4201b53b0, 0x0, 0x1581c80, 0xc4204becc0)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*UnixListener).accept(0xc420221c50, 0x30, 0xdc5420, 0xe91201)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc420221c50, 0xc4204bb200, 0xd05a00, 0x156e160, 0xacd159)
	/usr/local/go/src/net/unixsock.go:237 +0x49
github.com/weaveworks/weave/proxy.(*MalformedHostHeaderOverride).Accept(0xc420295040, 0xc4204bb1d0, 0xd05a00, 0x156e160, 0xdaa940)
	/go/src/github.com/weaveworks/weave/proxy/malformed_host_override.go:117 +0x37
net/http.(*Server).Serve(0xc4201db760, 0x1588540, 0xc420295040, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
github.com/weaveworks/weave/proxy.(*Proxy).Serve.func1(0xc4204c3200, 0xc420075080, 0x1588540, 0xc420295040)
	/go/src/github.com/weaveworks/weave/proxy/proxy.go:297 +0x7a
created by github.com/weaveworks/weave/proxy.(*Proxy).Serve
	/go/src/github.com/weaveworks/weave/proxy/proxy.go:298 +0x9d

goroutine 44 [syscall, 106 minutes]:
syscall.Syscall6(0x2d, 0x1f, 0xc42043c000, 0x1000, 0x0, 0xc4200215f0, 0xc4200215e4, 0x2b, 0x7f4addb6ccb0, 0x455c90)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x1f, 0xc42043c000, 0x1000, 0x1000, 0x0, 0xc4200215f0, 0xc4200215e4, 0x0, 0xc4201e8800, 0x2)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x99
syscall.Recvfrom(0x1f, 0xc42043c000, 0x1000, 0x1000, 0x0, 0x1000, 0xc4201cd780, 0xc420221e30, 0x7c4436, 0xc4200216e8)
	/usr/local/go/src/syscall/syscall_unix.go:252 +0xaf
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc420328a50, 0xe90ee0, 0xc420308900, 0xc42025d380, 0x0, 0x0)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:596 +0x97
github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.linkSubscribe.func2(0xc420308900, 0xc420328a50)
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:1187 +0x7f
created by github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink.linkSubscribe
	/go/src/github.com/weaveworks/weave/vendor/github.com/vishvananda/netlink/link_linux.go:1200 +0xb7

```

**Comment by brb** [comment]
Closing as it duplicates https://github.com/weaveworks/weave/issues/3124.

**Comment by brb** [comment]
In #3124 it hanged (not mentioned), and after a while it exited with 147. In both cases, the bridge creation is a suspect.
