### ISSUE TITLE
IPAM ring inconsistency reconcilliation fails when range crosses zero

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#3693]
E.g. at https://circleci.com/gh/weaveworks/weave/12331
https://circleci.com/gh/weaveworks/weave/12345
https://circleci.com/gh/weaveworks/weave/12377

It doesn't seem to say where it's failing:

```
>>> Running /home/circleci/src/github.com/weaveworks/weave/test/191_create_bridge_2_test.sh on [test-12331-0-3.us-central1-a.weave-net test-12331-0-4.us-central1-a.weave-net]
>>> Test /home/circleci/src/github.com/weaveworks/weave/test/191_create_bridge_2_test.sh finished after 33.9 secs with error: exit status 1
Re-create bridge after restart
f66a1219fda5e35241da6aa8e2771b6f0f5876e52a8be913970e82aff7a70202
fc08a2df8e7f6a43c9b9769aec5fde74993524eb5bce3f15c8fbc27c7083b71b
ac55848b4c8b317f2179ba0a9b0364d8e9480bf04d0164df52b9a559c0347b99
d2474e5825ccd172f8ad6e2814cc87594cf725dc90ec96567f13e710b393ff5a
05234413fec5275bc5e1279bcc19d67b2b82e77f8b8da5139cd9912345edcb7b
10.32.0.2
fcf6c0c74d838a0aae215c2b70c9f241ee19c0cf6aaa324d26fb6f84a334e817
10.32.0.1
```

Looks like it happens after the `expose`.

**Comment by bboreham** [comment]
Slightly different failure where we do see what happened: https://circleci.com/gh/weaveworks/weave/12381

```
>>> Test /home/circleci/src/github.com/weaveworks/weave/test/191_create_bridge_2_test.sh finished after 43.4 secs with error: exit status 1
Re-create bridge after restart
341ca41624aa402b786ae7d23212204f65a842b9c046e11ca685aa60924a2b58
d9c2b99a0cb3c929cb9779e558ab4c7e2ade83bbd783d2166293fb4cce354f67
9bc338e41c92bb04db6d993f94e26b5280f22d0f99a45f75139522205f61846e
e8e103a1f907154aaad63c5a1950b179036f46e6a67f3c26b07a6022f59cfb5d
6db0afb1eb98c020dab1a6d256d633263445200624416169d0988a007c9f9263
10.32.0.2
16f8255d722d0461f763419a37a8fa3f2281a22d2042bc1c280db2a7612dbc23
10.32.0.1
test #2 "exec_on test-12381-0-3.us-central1-a.weave-net c1 ping -nq -W 2 -c 1 10.32.0.3" failed:
	program terminated with code 1 instead of 0
1 of 7 tests failed in 41.109s.
```

**Comment by bboreham** [comment]
I managed to recreate the failure with `set -x` turned on - had to run it about ten times before it failed.
Apparently it is failing on the `kill -9` line

```
Re-create bridge after restart
cc67f1178d2b5514adb966f3f7f90c5ff8ac3912c0f1404c9ee4cd5abfa57f1d
969cf168649647658125d770e90d8b40547148afda01184fba1d9b0c91a32d64
09b27e0454706f13dab9856491a00d53d83541c286389f7d403e569bc66eaf08
628117be0effd81096c6178662529f12026e15ad08a66e1aadef767de1d9116e
4c28da024b34285c8c4391dee105586d5246c11e44db9a6664af706b20ee7203
10.32.0.2
a90a961f9cd8c92400a8bee83347f008c6ea8c0810c48217091af2166c7a6377
10.32.0.1
++ mktemp
+ IPT_BEFORE=/tmp/tmp.6H9aV96CCV
++ mktemp
+ IPT_AFTER=/tmp/tmp.MjdFifLtYc
+ run_on test-12381-0-3.us-central1-a.weave-net 'sudo iptables-save | grep -i weave | grep -v '\''\[.*:.*\]'\'' > /tmp/tmp.6H9aV96CCV'
+ host=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ '[' -z '' ']'
+ remote test-12381-0-3.us-central1-a.weave-net ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net 'sudo iptables-save | grep -i weave | grep -v '\''\[.*:.*\]'\'' > /tmp/tmp.6H9aV96CCV'
+ rem=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net 'sudo iptables-save | grep -i weave | grep -v '\''\[.*:.*\]'\'' > /tmp/tmp.6H9aV96CCV'
++ read line
+ run_on test-12381-0-3.us-central1-a.weave-net 'sudo iptables -t filter -D FORWARD -o weave -m comment --comment "NOTE: this must go before '\''-j KUBE-FORWARD'\''" -j WEAVE-NPC'
+ host=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ '[' -z '' ']'
+ remote test-12381-0-3.us-central1-a.weave-net ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net 'sudo iptables -t filter -D FORWARD -o weave -m comment --comment "NOTE: this must go before '\''-j KUBE-FORWARD'\''" -j WEAVE-NPC'
+ rem=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net 'sudo iptables -t filter -D FORWARD -o weave -m comment --comment "NOTE: this must go before '\''-j KUBE-FORWARD'\''" -j WEAVE-NPC'
++ read line
+ run_on test-12381-0-3.us-central1-a.weave-net sudo iptables -t nat -D POSTROUTING -j WEAVE
+ host=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ '[' -z '' ']'
+ remote test-12381-0-3.us-central1-a.weave-net ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net sudo iptables -t nat -D POSTROUTING -j WEAVE
+ rem=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net sudo iptables -t nat -D POSTROUTING -j WEAVE
++ read line
+ kill_weaver
+ run_on test-12381-0-3.us-central1-a.weave-net sudo ip link set weave down
+ host=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ '[' -z '' ']'
+ remote test-12381-0-3.us-central1-a.weave-net ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net sudo ip link set weave down
+ rem=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net sudo ip link set weave down
++ read line
++ container_pid test-12381-0-3.us-central1-a.weave-net weave
++ docker_on test-12381-0-3.us-central1-a.weave-net inspect -f '{{.State.Pid}}' weave
++ host=test-12381-0-3.us-central1-a.weave-net
++ shift 1
++ '[' -z '' ']'
++ docker -H tcp://test-12381-0-3.us-central1-a.weave-net:2375 inspect -f '{{.State.Pid}}' weave
+ WEAVER_PID=5565
+ run_on test-12381-0-3.us-central1-a.weave-net sudo kill -9 5565
+ host=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ '[' -z '' ']'
+ remote test-12381-0-3.us-central1-a.weave-net ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net sudo kill -9 5565
+ rem=test-12381-0-3.us-central1-a.weave-net
+ shift 1
+ ssh -l weaveworks-cit -i /home/circleci/.ssh/weaveworks_cit_id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o LogLevel=ERROR test-12381-0-3.us-central1-a.weave-net sudo kill -9 5565
++ read line
+ _assert_cleanup
+ local status=1
+ [[ 1 -eq 0 ]]
```

**Comment by bboreham** [comment]
Logs from a `weave` container after a failure like the above show it crashed; maybe this races with the `kill`?

```
INFO: 2019/08/29 16:56:12.166819 Command line options: map[docker-bridge:docker0 ipalloc-range:10.32.0.0/12 port:6783 status-addr:127.0.0.1:6782 host-root:/host nickname:test-12381-0-3 dns-listen-address:172.17.0.1:53 expect-npc:true H:[tcp://0.0.0.0:12375] datapath:datapath http-addr:127.0.0.1:6784 plugin:true proxy:true resolv-conf:/var/run/weave/etc/resolv.conf weave-bridge:weave]
INFO: 2019/08/29 16:56:12.170720 weave  unreleased
INFO: 2019/08/29 16:56:12.172623 Docker API on unix:///var/run/docker.sock: &[Arch=amd64 KernelVersion=4.13.0-1019-gcp Version=17.06.2-ce ApiVersion=1.30 GoVersion=go1.8.3 BuildTime=2017-09-05T19:59:11.118087934+00:00 MinAPIVersion=1.12 GitCommit=cec0b72 Os=linux]
INFO: 2019/08/29 16:56:12.178007 proxy listening on tcp://0.0.0.0:12375
INFO: 2019/08/29 16:56:12.274121 Bridge type is bridged_fastdp
INFO: 2019/08/29 16:56:12.274142 Communication between peers is unencrypted.
INFO: 2019/08/29 16:56:12.283837 Our name is 12:32:e3:c5:81:ce(test-12381-0-3)
INFO: 2019/08/29 16:56:12.283874 Launch detected - using supplied peer list: []
INFO: 2019/08/29 16:56:12.317998 Docker API on unix:///var/run/docker.sock: &[GoVersion=go1.8.3 BuildTime=2017-09-05T19:59:11.118087934+00:00 KernelVersion=4.13.0-1019-gcp Version=17.06.2-ce ApiVersion=1.30 MinAPIVersion=1.12 GitCommit=cec0b72 Os=linux Arch=amd64]
INFO: 2019/08/29 16:56:12.322250 Checking for pre-existing addresses on weave bridge
INFO: 2019/08/29 16:56:12.348833 [allocator 12:32:e3:c5:81:ce] No valid persisted data
INFO: 2019/08/29 16:56:12.358868 [allocator 12:32:e3:c5:81:ce] Initialising via deferred consensus
INFO: 2019/08/29 16:56:12.363968 Listening for DNS queries on 172.17.0.1:53
INFO: 2019/08/29 16:56:12.377230 Sniffing traffic on datapath (via ODP)
INFO: 2019/08/29 16:56:12.380451 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2019/08/29 16:56:12.380899 Listening for status+metrics requests on 127.0.0.1:6782
INFO: 2019/08/29 16:56:12.383485 Waiting for Weave API Server...
INFO: 2019/08/29 16:56:12.384553 Finished waiting for Weave API Server
INFO: 2019/08/29 16:56:12.384934 Listening on /run/docker/plugins/weave.sock for global scope
INFO: 2019/08/29 16:56:12.384989 Listening on /run/docker/plugins/weavemesh.sock for local scope
INFO: 2019/08/29 16:56:12.385044 Creating default "weave" network
INFO: 2019/08/29 16:56:12.402094 [ipam] RequestPool weavelocal 10.32.0.0/12  map[]
INFO: 2019/08/29 16:56:12.403617 [net] CreateNetwork c85947051287ce103fd3aa15fdf85a2739d243b9ce3b01d5c6b1475a62bd9578
INFO: 2019/08/29 16:56:13.073846 Assuming quorum size of 1
ERRO: 2019/08/29 16:56:15.811447 Interface "weave" which needs to be in UP state for Weave functioning is found to be in DOWN state
INFO: 2019/08/29 16:56:16.329137 ->[10.128.0.28:60533] connection accepted
INFO: 2019/08/29 16:56:16.329780 ->[10.128.0.28:60533|ba:2e:81:92:47:4f(test-12381-0-4)]: connection ready; using protocol version 2
INFO: 2019/08/29 16:56:16.329849 overlay_switch ->[ba:2e:81:92:47:4f(test-12381-0-4)] using sleeve
INFO: 2019/08/29 16:56:16.329878 ->[10.128.0.28:60533|ba:2e:81:92:47:4f(test-12381-0-4)]: connection added (new peer)
panic: Assertion failure

goroutine 135 [running]:
github.com/weaveworks/weave/common.Assert(0xc4204aee00)
	/go/src/github.com/weaveworks/weave/common/utils.go:8 +0x6c
github.com/weaveworks/weave/ipam.(*Allocator).assertInvariants(0xc4204aedc0)
	/go/src/github.com/weaveworks/weave/ipam/allocator.go:928 +0xd5
github.com/weaveworks/weave/ipam.(*Allocator).actorLoop(0xc4204aedc0, 0xc420470fc0, 0xc4200c8960)
	/go/src/github.com/weaveworks/weave/ipam/allocator.go:715 +0x96
created by github.com/weaveworks/weave/ipam.(*Allocator).Start
	/go/src/github.com/weaveworks/weave/ipam/allocator.go:183 +0x1e0
INFO: 2019/08/29 16:56:16.708699 Command line options: map[host-root:/host plugin:true status-addr:127.0.0.1:6782 dns-listen-address:172.17.0.1:53 docker-bridge:docker0 H:[tcp://0.0.0.0:12375] weave-bridge:weave expect-npc:true http-addr:127.0.0.1:6784 nickname:test-12381-0-3 port:6783 resolv-conf:/var/run/weave/etc/resolv.conf datapath:datapath ipalloc-range:10.32.0.0/12 proxy:true]
INFO: 2019/08/29 16:56:16.712301 weave  unreleased
INFO: 2019/08/29 16:56:16.716048 Docker API on unix:///var/run/docker.sock: &[GoVersion=go1.8.3 Os=linux Arch=amd64 BuildTime=2017-09-05T19:59:11.118087934+00:00 Version=17.06.2-ce ApiVersion=1.30 MinAPIVersion=1.12 GitCommit=cec0b72 KernelVersion=4.13.0-1019-gcp]
INFO: 2019/08/29 16:56:16.723582 proxy listening on tcp://0.0.0.0:12375
INFO: 2019/08/29 16:56:16.807601 Re-exposing 10.32.0.1/12 on bridge "weave"
INFO: 2019/08/29 16:56:16.816017 Bridge type is bridged_fastdp
INFO: 2019/08/29 16:56:16.816036 Communication between peers is unencrypted.
INFO: 2019/08/29 16:56:16.842438 Our name is 12:32:e3:c5:81:ce(test-12381-0-3)
INFO: 2019/08/29 16:56:16.842876 Restart/resume detected - using persisted peer list: []
INFO: 2019/08/29 16:56:16.854455 Docker API on unix:///var/run/docker.sock: &[Version=17.06.2-ce Os=linux GoVersion=go1.8.3 Arch=amd64 KernelVersion=4.13.0-1019-gcp BuildTime=2017-09-05T19:59:11.118087934+00:00 ApiVersion=1.30 MinAPIVersion=1.12 GitCommit=cec0b72]
INFO: 2019/08/29 16:56:16.855798 Checking for pre-existing addresses on weave bridge
INFO: 2019/08/29 16:56:16.855954 weave bridge has address 10.32.0.1/12
INFO: 2019/08/29 16:56:16.860186 [allocator 12:32:e3:c5:81:ce] Initialising with persisted data
ERRO: 2019/08/29 16:56:16.860300 [allocator] address 10.32.0.1/12 is owned by other peer ba:2e:81:92:47:4f
INFO: 2019/08/29 16:56:16.861793 Listening for DNS queries on 172.17.0.1:53
INFO: 2019/08/29 16:56:16.868207 Sniffing traffic on datapath (via ODP)
INFO: 2019/08/29 16:56:16.871609 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2019/08/29 16:56:16.872026 Listening for status+metrics requests on 127.0.0.1:6782
INFO: 2019/08/29 16:56:16.872100 Waiting for Weave API Server...
INFO: 2019/08/29 16:56:16.873004 Finished waiting for Weave API Server
INFO: 2019/08/29 16:56:16.873063 Listening on /run/docker/plugins/weave.sock for global scope
INFO: 2019/08/29 16:56:16.873099 Listening on /run/docker/plugins/weavemesh.sock for local scope
INFO: 2019/08/29 16:56:16.873107 Creating default "weave" network
ERRO: 2019/08/29 16:56:21.860686 [allocator] address 10.32.0.1/12 is owned by other peer ba:2e:81:92:47:4f
INFO: 2019/08/29 16:56:26.173182 ->[10.128.0.28:50403] connection accepted
INFO: 2019/08/29 16:56:26.173720 ->[10.128.0.28:50403|ba:2e:81:92:47:4f(test-12381-0-4)]: connection ready; using protocol version 2
INFO: 2019/08/29 16:56:26.173807 overlay_switch ->[ba:2e:81:92:47:4f(test-12381-0-4)] using sleeve
INFO: 2019/08/29 16:56:26.173837 ->[10.128.0.28:50403|ba:2e:81:92:47:4f(test-12381-0-4)]: connection added (new peer)
INFO: 2019/08/29 16:56:26.191639 ->[10.128.0.28:50403|ba:2e:81:92:47:4f(test-12381-0-4)]: connection fully established
INFO: 2019/08/29 16:56:26.192429 sleeve ->[10.128.0.28:6783|ba:2e:81:92:47:4f(test-12381-0-4)]: Effective MTU verified at 1398
INFO: 2019/08/29 16:56:45.946942 Discovered remote MAC ba:2e:81:92:47:4f at ba:2e:81:92:47:4f(test-12381-0-4)
INFO: 2019/08/29 16:56:45.947465 Discovered remote MAC b6:51:13:73:2f:2d at ba:2e:81:92:47:4f(test-12381-0-4)
```

**Comment by bboreham** [comment]
What happens in this test is:
- Two nodes host1 and host2 connect.  Both allocate an IP address to a container, so both have entries in the ring.
- Script calls `weave reset` on host1, deleting persisted ipam data.
- Script then calls `weave launch` on host1 without mentioning host2, so host2 will eventually reconnect.
- Script also calls `weave expose` on host1, which allocates an address.

Depending on the ordering between `expose` and reconnect, host1 and host2 may end up with inconsistent rings, which leads to the panic.  The reason the script fails silently is a race between fetching the pid and the process restarting after panic.

The reason for the panic is that the call to `checkRangeHasAllocations()` gives the wrong answer for the "whole universe" range `10.32.0.0->10.32.0.0`.
