### ISSUE TITLE
Error launching weave as systemd service

### ISSUE THREAD

**Issue by seimic** [weaveworks/weave#3903]
## What you expected to happen?

Weave network between 3 servers running docker.
After initial setup some meaningful output in 'weave status'
Basically the following installation: https://www.weave.works/docs/net/latest/install/systemd/

## What happened?

Weave container reports errors (see logs) and 'weave status' reports 'curl: (52) Empty reply from server'

## How to reproduce it?

```
sudo curl -L git.io/weave -o /usr/local/bin/weave
sudo chmod a+x /usr/local/bin/weave

sudo tee -a /etc/systemd/system/weave.service << EOF > /dev/null
[Unit]
Description=Weave Network
Documentation=http://docs.weave.works/weave/latest_release/
Requires=docker.service
After=docker.service
[Service]
EnvironmentFile=-/etc/sysconfig/weave
ExecStartPre=/usr/local/bin/weave launch --no-restart $PEERS
ExecStart=/usr/bin/docker attach weave
ExecStop=/usr/local/bin/weave stop
[Install]
WantedBy=multi-user.target
EOF

sudo mkdir -p /etc/sysconfig
sudo tee -a /etc/sysconfig/weave << EOF > /dev/null
PEERS="..."  <- On server1: "10.0.1.12 10.0.1.13", server2: "10.0.1.11 10.0.1.13", server3: "10.0.1.11 10.0.1.12" 
WEAVE_PASSWORD="..."
EOF

sudo systemctl start weave
sudo systemctl enable weave
```

## Anything else we need to know?

The network connection between the three nodes works fine. All three nodes are in the same subnet 10.0.1.0/24
No firewall restrictions on this local network by now.

### Weave:
  weave script 2.8.1
  weave 2.8.1
### Docker:
  20.10.6
### Linux:
  Ubuntu 20.04 LTS
  Kernel: 5.4.0-73-generic

## Logs:

```
INFO: 2021/05/24 08:43:23.843666 Command line options: map[H:[unix:///var/run/weave/weave.sock] datapath:datapath dns-listen-address:172.17.0.1:53 docker-bridge:docker0 host-root:/host http-addr:127.0.0.1:6784 ipalloc-range:10.32.0.0/12 nickname:forisfsn02 plugin:true port:6783 proxy:true resolv-conf:/var/run/weave/etc/stub-resolv.conf status-addr:127.0.0.1:6782 weave-bridge:weave]
INFO: 2021/05/24 08:43:23.843696 weave  2.8.1
INFO: 2021/05/24 08:43:23.856788 Docker API on unix:///var/run/docker.sock: &[GoVersion=go1.13.15 Os=linux Arch=amd64 Platform={"Name":"Docker Engine - Community"} Components=[{"Details":{"ApiVersion":"1.41","Arch":"amd64","BuildTime":"2021-04-09T22:45:28.000000000+00:00","Experimental":"false","GitCommit":"8728dd2","GoVersion":"go1.13.15","KernelVersion":"5.4.0-73-generic","MinAPIVersion":"1.12","Os":"linux"},"Name":"Engine","Version":"20.10.6"},{"Details":{"GitCommit":"05f951a3781f4f2c1911b05e61c160e9c30eaa8e"},"Name":"containerd","Version":"1.4.4"},{"Details":{"GitCommit":"12644e614e25b05da6fd08a38ffa0cfe1903fdec"},"Name":"runc","Version":"1.0.0-rc93"},{"Details":{"GitCommit":"de40ad0"},"Name":"docker-init","Version":"0.19.0"}] Version=20.10.6 ApiVersion=1.41 MinAPIVersion=1.12 GitCommit=8728dd2 KernelVersion=5.4.0-73-generic BuildTime=2021-04-09T22:45:28.000000000+00:00]
INFO: 2021/05/24 08:43:23.865264 proxy listening on unix:///var/run/weave/weave.sock
INFO: 2021/05/24 08:43:24.192296 Bridge type is bridged_fastdp
INFO: 2021/05/24 08:43:24.192320 Communication between peers via untrusted networks is encrypted.
INFO: 2021/05/24 08:43:24.225324 Our name is [REDACTED]
INFO: 2021/05/24 08:43:24.225364 Launch detected - using supplied peer list: []
INFO: 2021/05/24 08:43:24.238319 Docker API on unix:///var/run/docker.sock: &[ApiVersion=1.41 MinAPIVersion=1.12 GoVersion=go1.13.15 Arch=amd64 BuildTime=2021-04-09T22:45:28.000000000+00:00 Platform={"Name":"Docker Engine - Community"} Components=[{"Details":{"ApiVersion":"1.41","Arch":"amd64","BuildTime":"2021-04-09T22:45:28.000000000+00:00","Experimental":"false","GitCommit":"8728dd2","GoVersion":"go1.13.15","KernelVersion":"5.4.0-73-generic","MinAPIVersion":"1.12","Os":"linux"},"Name":"Engine","Version":"20.10.6"},{"Details":{"GitCommit":"05f951a3781f4f2c1911b05e61c160e9c30eaa8e"},"Name":"containerd","Version":"1.4.4"},{"Details":{"GitCommit":"12644e614e25b05da6fd08a38ffa0cfe1903fdec"},"Name":"runc","Version":"1.0.0-rc93"},{"Details":{"GitCommit":"de40ad0"},"Name":"docker-init","Version":"0.19.0"}] Version=20.10.6 GitCommit=8728dd2 Os=linux KernelVersion=5.4.0-73-generic]
INFO: 2021/05/24 08:43:24.245021 Checking for pre-existing addresses on weave bridge
INFO: 2021/05/24 08:43:24.249436 [allocator [REDACTED]] No valid persisted data
INFO: 2021/05/24 08:43:24.260628 [allocator [REDACTED]] Initialising via deferred consensus
INFO: 2021/05/24 08:43:24.261937 Listening for DNS queries on 172.17.0.1:53
INFO: 2021/05/24 08:43:24.264692 Sniffing traffic on datapath (via ODP)
INFO: 2021/05/24 08:43:24.267327 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2021/05/24 08:43:24.267463 Listening for status+metrics requests on 127.0.0.1:6782
INFO: 2021/05/24 08:43:24.267492 Waiting for Weave API Server...
2021/05/24 08:43:24 http: panic serving 127.0.0.1:44180: runtime error: slice bounds out of range [:9] with length 8
goroutine 226 [running]:
net/http.(*conn).serve.func1(0xc0006a8000)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x11fe5c0, 0xc0006a2380)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/miekg/dns.ClientConfigFromReader(0x1405680, 0xc0006a6008, 0x0, 0x0, 0xc0006a6008)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/clientconfig.go:94 +0x84f
github.com/miekg/dns.ClientConfigFromFile(0x7ffee092fedf, 0x23, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/clientconfig.go:29 +0xc8
github.com/weaveworks/weave/nameserver.(*upstream).Config(0xc000446d80, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:66 +0x1a5
github.com/weaveworks/weave/nameserver.NewStatus(0xc0003867e0, 0xc000386850, 0x0)
        /go/src/github.com/weaveworks/weave/nameserver/status.go:39 +0x2bb
main.HandleHTTP.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/prog/weaver/http.go:315 +0x137
main.HandleHTTP.func4.1(0x141a5c0, 0xc000166000, 0xc0004fc400)
        /go/src/github.com/weaveworks/weave/prog/weaver/http.go:359 +0x44
net/http.HandlerFunc.ServeHTTP(0xc0004069a0, 0x141a5c0, 0xc000166000, 0xc0004fc400)
        /usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d6850, 0x141a5c0, 0xc000166000, 0xc0004fc200)
        /go/src/github.com/weaveworks/weave/vendor/github.com/gorilla/mux/mux.go:159 +0x106
github.com/weaveworks/weave/common.(*loggingHandler).ServeHTTP(0xc00022d080, 0x141a5c0, 0xc000166000, 0xc0004fc200)
        /go/src/github.com/weaveworks/weave/common/http.go:13 +0x151
net/http.(*ServeMux).ServeHTTP(0x1b61500, 0x141a5c0, 0xc000166000, 0xc0004fc200)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00026ac40, 0x141a5c0, 0xc000166000, 0xc0004fc200)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0006a8000, 0x141dd80, 0xc0006aa000)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
INFO: 2021/05/24 08:43:26.268821 Finished waiting for Weave API Server
INFO: 2021/05/24 08:43:26.268884 Listening on /run/docker/plugins/weave.sock for global scope
INFO: 2021/05/24 08:43:26.268914 Listening on /run/docker/plugins/weavemesh.sock for local scope
INFO: 2021/05/24 08:43:26.268923 Creating default "weave" network
INFO: 2021/05/24 08:43:26.270148 [net] GetCapabilities 
INFO: 2021/05/24 08:43:26.270318 [ipam] GetCapabilities
INFO: 2021/05/24 08:43:26.270468 [ipam] GetDefaultAddressSpaces
INFO: 2021/05/24 08:43:26.270681 [ipam] RequestPool weavelocal 10.32.0.0/12  map[]
INFO: 2021/05/24 08:43:26.271080 [net] CreateNetwork 5e46808b4e7082a8c8f457b09f12674bd8620835c02da036b236add45dcda86c
2021/05/24 09:13:55 http: panic serving 127.0.0.1:44222: runtime error: slice bounds out of range [:9] with length 8
goroutine 687 [running]:
net/http.(*conn).serve.func1(0xc0006a8000)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x11fe5c0, 0xc0006a2400)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/miekg/dns.ClientConfigFromReader(0x1405680, 0xc0000ac130, 0x0, 0x0, 0xc0000ac130)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/clientconfig.go:94 +0x84f
github.com/miekg/dns.ClientConfigFromFile(0x7ffee092fedf, 0x23, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/clientconfig.go:29 +0xc8
github.com/weaveworks/weave/nameserver.(*upstream).Config(0xc000446d80, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:66 +0x1a5
github.com/weaveworks/weave/nameserver.NewStatus(0xc0003867e0, 0xc000386850, 0x0)
        /go/src/github.com/weaveworks/weave/nameserver/status.go:39 +0x2bb
main.HandleHTTP.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/prog/weaver/http.go:315 +0x137
main.HandleHTTP.func4.1(0x141a5c0, 0xc000166000, 0xc0004c8500)
        /go/src/github.com/weaveworks/weave/prog/weaver/http.go:359 +0x44
net/http.HandlerFunc.ServeHTTP(0xc0004069a0, 0x141a5c0, 0xc000166000, 0xc0004c8500)
        /usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d6850, 0x141a5c0, 0xc000166000, 0xc0004c8200)
        /go/src/github.com/weaveworks/weave/vendor/github.com/gorilla/mux/mux.go:159 +0x106
github.com/weaveworks/weave/common.(*loggingHandler).ServeHTTP(0xc00022d080, 0x141a5c0, 0xc000166000, 0xc0004c8200)
        /go/src/github.com/weaveworks/weave/common/http.go:13 +0x151
net/http.(*ServeMux).ServeHTTP(0x1b61500, 0x141a5c0, 0xc000166000, 0xc0004c8200)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00026ac40, 0x141a5c0, 0xc000166000, 0xc0004c8200)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0006a8000, 0x141dd80, 0xc001f2c0c0)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
```

**Comment by krk628** [comment]
evidently weave doesn't like "options edns0 trust-ad" line in the docker hosts /etc/resolv.conf file (length of options exceeds 8 characters?).  The issue will go away if you remove the "trust-ad" bit from the stub resolver config.  I don't know how to do so, don't care, and don't need the stub resolver so I fixed the issue by bypassing it and creating a traditional resolv.conf.  ymmv as disabling the stub resolver has implications specific to your site.  Good luck

```
rm -f /etc/resolv.conf
echo "nameserver 10.10.10.1" > /etc/resolv.conf   # replace with your nameserver IP and other resolv.conf options

```

**Comment by lubars** [comment]
This issue is discussed in #3868. During weave install we do:

`sudo sed -i -e "s/trust-ad//g" /etc/resolv.conf`

**Comment by seimic** [comment]
Hi, 

thanks, but I decided finally to go with another solution in the past (cilium). 
We were using weave as cni in our old rke1 kubernetes clusters before, for this I wanted to give it a try in LAN as described above. Cilium worked out of the box... and of course, still does. :) 

Kind regards,
Michael
