### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by johnfelipe** [weaveworks/weave#3952]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5431465f-7fff-d07e-1ab1-d2d0850ff07c"><div dir="ltr" style="margin-left:0pt;" align="left">

Host name | IP
-- | --
felipe | 192.168.0.14
ubuntu20dockers | 192.168.88.186

</div><br /></b>
</body>
</html>

 <hr>

**felipe**

```
sudo su

ip addres | grep dynamic

    inet 192.168.0.14/24 brd 192.168.0.255 scope global dynamic ens33
```

next

```
sudo curl -L git.io/weave -o /usr/local/bin/weave

sudo chmod a+x /usr/local/bin/weave

weave launch 192.168.88.186

```

0b87ebe4eb2fa79b74ece8eb42988c6706e93a9edae64dd99ae6ace1c0f3b7db

here issue

```
root@ubuntu20dockers:~# weave status connections
curl: (52) Empty reply from server
```

 <hr>

**ubuntu20dockers**

do this

```
sudo curl -L git.io/weave -o /usr/local/bin/weave

sudo chmod a+x /usr/local/bin/weave

weave launch 192.168.0.14

```

```
docker network ls

NETWORK ID     NAME                             DRIVER      SCOPE
679706fb2674   bridge                           bridge      local
8b74b15b3081   cassandra-cluster_cassandranet   bridge      local
fc27b3aeed94   clickhouse_default               bridge      local
f0a880d6cd18   host                             host        local
d7a4861d0681   my-stack_mynet                   bridge      local
7bb4289bf490   none                             null        local
c40acb60e412   rocketchat_default               bridge      local
b381cd33317e   weave                            weavemesh   local

```
here issue

```
root@felipe:~# weave status connections
curl: (52) Empty reply from server
```

**Comment by sms-system** [comment]
Hi! I had the same problem. And on errors, the `docker logs weave` command outputs this:
```
2022/08/19 18:18:09 http: panic serving 127.0.0.1:60970: runtime error: slice bounds out of range [:9] with length 8
goroutine 2068 [running]:
net/http.(*conn).serve.func1(0xc0000b74a0)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x11fe5c0, 0xc0004e5fe0)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/miekg/dns.ClientConfigFromReader(0x1405760, 0xc0004141b0, 0x0, 0x0, 0xc0004141b0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/clientconfig.go:94 +0x84f
github.com/miekg/dns.ClientConfigFromFile(0x7ffc49b54f03, 0x23, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/vendor/github.com/miekg/dns/clientconfig.go:29 +0xc8
github.com/weaveworks/weave/nameserver.(*upstream).Config(0xc000138f60, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/nameserver/dns.go:66 +0x1a5
github.com/weaveworks/weave/nameserver.NewStatus(0xc0003e0000, 0xc0003e0070, 0x0)
        /go/src/github.com/weaveworks/weave/nameserver/status.go:39 +0x2bb
main.HandleHTTP.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/weaveworks/weave/prog/weaver/http.go:320 +0x330
main.HandleHTTP.func4.1(0x141a6a0, 0xc001a63260, 0xc0003dc100)
        /go/src/github.com/weaveworks/weave/prog/weaver/http.go:366 +0x44
net/http.HandlerFunc.ServeHTTP(0xc0004110c0, 0x141a6a0, 0xc001a63260, 0xc0003dc100)
        /usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003e0c40, 0x141a6a0, 0xc001a63260, 0xc000611f00)
        /go/src/github.com/weaveworks/weave/vendor/github.com/gorilla/mux/mux.go:159 +0x106
github.com/weaveworks/weave/common.(*loggingHandler).ServeHTTP(0xc000060da0, 0x141a6a0, 0xc001a63260, 0xc000611f00)
        /go/src/github.com/weaveworks/weave/common/http.go:13 +0x151
net/http.(*ServeMux).ServeHTTP(0x1b61500, 0x141a6a0, 0xc001a63260, 0xc000611f00)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0000fc0e0, 0x141a6a0, 0xc001a63260, 0xc000611f00)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000b74a0, 0x141de60, 0xc000035700)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
```

I found the source of problem in https://github.com/miekg/dns library. And as I understand this was already fixed there (https://github.com/miekg/dns/pull/642). But weave still using old version of library.

When I updated the dependency to the latest version the problem with `Empty reply from server` disappeared.

**Comment by utybo** [comment]
Hi @sms-system, thanks for your discovery! do you happen to have a fork somewhere I could build and run to fix this issue? I have zero knowledge of Go or how to build weave sadly :/

**Comment by lchunleo** [comment]
Facing the same issue ..is the fix in the latest version?
