### ISSUE TITLE
[dns] obscure test failure in absence of network connection

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#481]
````
--- FAIL: TestSimpleQuery (0.00s)
	util.go:87: Unexpected error: listen udp 224.0.0.251: setsockopt: no such device
		goroutine 13 [running]:
		github.com/zettio/weave/testing.stackTrace(0x2b3375f79b00, 0x0, 0x0)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:96 +0x88
		github.com/zettio/weave/testing.StackTrace(0x0, 0x0)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:91 +0x35
		github.com/zettio/weave/testing.Fatalf(0xc20806c630, 0x883610, 0x14, 0xc20807bd48, 0x1, 0x1)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:87 +0x27
		github.com/zettio/weave/testing.AssertNoErr(0xc20806c630, 0x2b3375f79b00, 0xc208033000)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:24 +0xea
		github.com/zettio/weave/nameserver.setup(0xc20806c630, 0x1, 0x1, 0x0, 0x0)
			/home/matthias/go/src/github.com/zettio/weave/nameserver/mdns_client_test.go:79 +0xbd
		github.com/zettio/weave/nameserver.TestSimpleQuery(0xc20806c630)
			/home/matthias/go/src/github.com/zettio/weave/nameserver/mdns_client_test.go:111 +0x11a
		testing.tRunner(0xc20806c630, 0xa4c5f8)
			/usr/local/go/src/testing/testing.go:447 +0xbf
		created by testing.RunTests
			/usr/local/go/src/testing/testing.go:555 +0xa8b
````
The root cause appears to be the call to `net.ListenMulticastUDP("udp", ifi, ipv4Addr)`, which supplies a nil interface, which according to the docs means "uses default multicast interface". I'm guessing that my machine only gets one of these when connected to a network.

This may not be easily fixable, but perhaps the tests relying on such an interface should be skipped when it is absent, or at least a more informative error should be produced.

**Comment by inercia** [comment]
I get the same error when you do not have connectivity. In that case, we could abort and print more information on the reason (_WeaveDNS_ tests would be useless though).
