### ISSUE TITLE
sched_queue_test.go fails with wrong number of calls

### ISSUE THREAD

**Issue by inercia** [weaveworks/weave#944]
`sched_queue_test.go` fails sometimes with _"expected X and got X+/-1"_ errors.

```
--- FAIL: TestSchedCallsGap-4 (0.01s)
	sched_queue_test.go:62: Now: 1970-01-01 00:16:40 +0000 UTC - calls: 900
	util.go:134: Expected Number of calls 901 but got 900
		goroutine 33 [running]:
		github.com/weaveworks/weave/testing.stackTrace(0xc20809e000, 0x0, 0x0)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:143 +0x88
		github.com/weaveworks/weave/testing.StackTrace(0x0, 0x0)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:138 +0x35
		github.com/weaveworks/weave/testing.Fatalf(0xc208090090, 0x583170, 0x19, 0xc20806de08, 0x3, 0x3)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:134 +0x27
		github.com/weaveworks/weave/testing.AssertEqualInt(0xc208090090, 0x384, 0x385, 0x56c190, 0xf)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:51 +0x1b3
		github.com/weaveworks/weave/common.TestSchedCallsGap(0xc208090090)
			/home/travis/gopath/src/github.com/weaveworks/weave/common/sched_queue_test.go:63 +0x55c
		testing.tRunner(0xc208090090, 0x6201b8)
			/usr/local/go/src/testing/testing.go:447 +0xbf
		created by testing.RunTests
			/usr/local/go/src/testing/testing.go:555 +0xa8b
INFO: 2015/06/16 18:58:06.106500 TestSchedCallsStop starting
FAIL
coverage: 73.3% of statements
FAIL	github.com/weaveworks/weave/common	0.030s
ok  	github.com/weaveworks/weave/ipam	7.379s	coverage: 67.5% of statements
ok  	github.com/weaveworks/weave/ipam/paxos	3.669s	coverage: 96.4% of statements
ok  	github.com/weaveworks/weave/ipam/ring	1.718s	coverage: 90.4% of statements
ok  	github.com/weaveworks/weave/ipam/space	0.003s	coverage: 71.6% of statements
ok  	github.com/weaveworks/weave/nameserver	18.372s	coverage: 84.3% of statements
ok  	github.com/weaveworks/weave/net	0.003s	coverage: 5.3% of statements
ok  	github.com/weaveworks/weave/router	0.378s	coverage: 28.9% of statements
make: *** [tests] Error 1
```

**Comment by rade** [comment]
any clues yet?

**Comment by inercia** [comment]
nothing yet... it is a low-frequency bug (about 1 in 2000 runs of the unit tests), so it is difficult to try new things...

**Comment by inercia** [comment]
This will be gone once the gossip DNS is in place...

**Comment by rade** [comment]
> This will be gone once the gossip DNS is in place...

but it's not in place yet. -> re-opening.
