### ISSUE TITLE
''No entries for peer found' failure in TestTransfer-4

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#982]
From the [Travis CI report](https://travis-ci.org/weaveworks/weave/builds/67902970)...

````
--- FAIL: TestTransfer-4 (1.01s)
	util.go:134: Expected success, got 'No entries for peer found'
		goroutine 10 [running]:
		github.com/weaveworks/weave/testing.stackTrace(0x2adaf7e2b900, 0x0, 0x0)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:143 +0x88
		github.com/weaveworks/weave/testing.StackTrace(0x0, 0x0)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:138 +0x35
		github.com/weaveworks/weave/testing.Fatalf(0xc20807e5a0, 0x9a03b0, 0x1a, 0xc20913ed90, 0x1, 0x1)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:134 +0x27
		github.com/weaveworks/weave/testing.AssertSuccess(0xc20807e5a0, 0x2adaf7e384c0, 0xc2091052c0)
			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:114 +0x11a
		github.com/weaveworks/weave/ipam.TestTransfer(0xc20807e5a0)
			/home/travis/gopath/src/github.com/weaveworks/weave/ipam/allocator_test.go:264 +0x6cf
		testing.tRunner(0xc20807e5a0, 0xddcf98)
			/usr/local/go/src/testing/testing.go:447 +0xbf
		created by testing.RunTests
			/usr/local/go/src/testing/testing.go:555 +0xa8b
````

NB: the test was run against a branch off 1.0, though I doubt that makes a difference.

**Comment by bboreham** [comment]
I think there are at least two problems in this test: 
1. no synchronisation between asynch senders and receivers 
2. the mock gossip router has the behaviour that it drops messages which cannot immediately be delivered

**Comment by rade** [comment]
I've put this into 1.0.2 on the grounds that we don't want the 1.0 branch to fail in CI for no good reason.
